-- T4KASH - PostgreSQL schema
-- Migration from the original SQL Server model.
-- Run after creating the database:
--   CREATE DATABASE t4kash;
--   psql -U postgres -d t4kash -f schema-postgresql.sql

BEGIN;

DROP TABLE IF EXISTS archivos_adjuntos CASCADE;
DROP TABLE IF EXISTS auditoria_sistema CASCADE;
DROP TABLE IF EXISTS calificaciones CASCADE;
DROP TABLE IF EXISTS comentarios_entrega CASCADE;
DROP TABLE IF EXISTS conexiones_usuarios CASCADE;
DROP TABLE IF EXISTS conversaciones CASCADE;
DROP TABLE IF EXISTS entregas CASCADE;
DROP TABLE IF EXISTS historial_estados CASCADE;
DROP TABLE IF EXISTS intentos_login CASCADE;
DROP TABLE IF EXISTS mensajes CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS pagos CASCADE;
DROP TABLE IF EXISTS portafolio CASCADE;
DROP TABLE IF EXISTS postulaciones CASCADE;
DROP TABLE IF EXISTS publicaciones CASCADE;
DROP TABLE IF EXISTS recomendaciones CASCADE;
DROP TABLE IF EXISTS reportes CASCADE;
DROP TABLE IF EXISTS revisiones_entrega CASCADE;
DROP TABLE IF EXISTS sesiones_usuario CASCADE;
DROP TABLE IF EXISTS tareas_habilidades CASCADE;
DROP TABLE IF EXISTS tokens_recuperacion_password CASCADE;
DROP TABLE IF EXISTS trabajos_asignados CASCADE;
DROP TABLE IF EXISTS transacciones_pago CASCADE;
DROP TABLE IF EXISTS usuario_roles CASCADE;
DROP TABLE IF EXISTS usuarios_estudiantes CASCADE;
DROP TABLE IF EXISTS usuarios_habilidades CASCADE;
DROP TABLE IF EXISTS verificaciones_usuario CASCADE;
DROP TABLE IF EXISTS tareas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS carreras CASCADE;
DROP TABLE IF EXISTS universidades CASCADE;
DROP TABLE IF EXISTS categorias_tarea CASCADE;
DROP TABLE IF EXISTS habilidades CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE universidades (
    id_universidad integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_universidad varchar(150) NOT NULL,
    dominio_correo varchar(100) NOT NULL,
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_universidades PRIMARY KEY (id_universidad),
    CONSTRAINT uq_universidades_dominio_correo UNIQUE (dominio_correo)
);

CREATE TABLE carreras (
    id_carrera integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_carrera varchar(120) NOT NULL,
    id_universidad integer NOT NULL,
    CONSTRAINT pk_carreras PRIMARY KEY (id_carrera)
);

CREATE TABLE roles (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_rol varchar(50) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_rol),
    CONSTRAINT uq_roles_nombre_rol UNIQUE (nombre_rol)
);

CREATE TABLE usuarios (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(80) NOT NULL,
    apellido varchar(80) NOT NULL,
    correo varchar(150) NOT NULL,
    documento_identidad varchar(20),
    password_hash varchar(255) NOT NULL,
    telefono varchar(25),
    direccion varchar(150),
    fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_usuario varchar(30) NOT NULL DEFAULT 'ACTIVO',
    id_universidad integer,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo)
);

CREATE TABLE usuario_roles (
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    CONSTRAINT pk_usuario_roles PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE usuarios_estudiantes (
    id_usuario integer NOT NULL,
    id_carrera integer,
    carnet_universitario varchar(50),
    estado_perfil_estudiante varchar(30) NOT NULL DEFAULT 'INCOMPLETO',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_estudiantes PRIMARY KEY (id_usuario)
);

CREATE TABLE habilidades (
    id_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_habilidad varchar(100) NOT NULL,
    descripcion varchar(250),
    estado boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_habilidades PRIMARY KEY (id_habilidad),
    CONSTRAINT uq_habilidades_nombre_habilidad UNIQUE (nombre_habilidad)
);

CREATE TABLE usuarios_habilidades (
    id_usuario_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_habilidad integer NOT NULL,
    nivel varchar(30) NOT NULL,
    descripcion varchar(250),
    verificada boolean NOT NULL DEFAULT false,
    fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_habilidades PRIMARY KEY (id_usuario_habilidad),
    CONSTRAINT uq_usuarios_habilidades_usuario_habilidad UNIQUE (id_usuario, id_habilidad)
);

CREATE TABLE categorias_tarea (
    id_categoria integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria varchar(100) NOT NULL,
    descripcion varchar(250),
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_categorias_tarea PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categorias_tarea_nombre_categoria UNIQUE (nombre_categoria)
);

CREATE TABLE tareas (
    id_tarea integer GENERATED BY DEFAULT AS IDENTITY,
    titulo varchar(150) NOT NULL,
    descripcion text NOT NULL,
    presupuesto numeric(10,2) NOT NULL,
    fecha_publicacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_limite_postulacion timestamp,
    fecha_limite timestamp,
    estado_tarea varchar(30) NOT NULL DEFAULT 'PUBLICADA',
    id_categoria integer NOT NULL,
    id_cliente integer NOT NULL,
    tipo_oportunidad varchar(50) NOT NULL,
    modalidad varchar(30),
    visibilidad varchar(30) NOT NULL DEFAULT 'PUBLICA',
    direccion_referencia varchar(250),
    latitud numeric(9,6),
    longitud numeric(9,6),
    CONSTRAINT pk_tareas PRIMARY KEY (id_tarea),
    CONSTRAINT ck_tareas_presupuesto CHECK (presupuesto >= 0),
    CONSTRAINT ck_tareas_coordenadas_validas CHECK (
        (latitud IS NULL AND longitud IS NULL)
        OR (
            latitud IS NOT NULL
            AND longitud IS NOT NULL
            AND latitud BETWEEN -90 AND 90
            AND longitud BETWEEN -180 AND 180
        )
    )
);

CREATE TABLE tareas_habilidades (
    id_tarea_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_habilidad integer NOT NULL,
    es_requerida boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tareas_habilidades PRIMARY KEY (id_tarea_habilidad),
    CONSTRAINT uq_tareas_habilidades_tarea_habilidad UNIQUE (id_tarea, id_habilidad)
);

CREATE TABLE postulaciones (
    id_postulacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_estudiante integer NOT NULL,
    mensaje varchar(500),
    precio_propuesto numeric(10,2),
    fecha_postulacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_postulacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT pk_postulaciones PRIMARY KEY (id_postulacion),
    CONSTRAINT uq_postulaciones_tarea_estudiante UNIQUE (id_tarea, id_estudiante),
    CONSTRAINT ck_postulaciones_precio CHECK (precio_propuesto IS NULL OR precio_propuesto >= 0)
);

CREATE TABLE trabajos_asignados (
    id_trabajo integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_estudiante integer NOT NULL,
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_entrega_esperada timestamp,
    estado_trabajo varchar(30) NOT NULL DEFAULT 'EN_PROCESO',
    CONSTRAINT pk_trabajos_asignados PRIMARY KEY (id_trabajo),
    CONSTRAINT uq_trabajos_asignados_tarea UNIQUE (id_tarea)
);

CREATE TABLE entregas (
    id_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    descripcion_entrega text NOT NULL,
    fecha_entrega timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_entrega varchar(30) NOT NULL DEFAULT 'ENVIADA',
    CONSTRAINT pk_entregas PRIMARY KEY (id_entrega)
);

CREATE TABLE comentarios_entrega (
    id_comentario_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_entrega integer NOT NULL,
    id_usuario integer NOT NULL,
    comentario varchar(700) NOT NULL,
    tipo_comentario varchar(40) NOT NULL,
    fecha_comentario timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comentarios_entrega PRIMARY KEY (id_comentario_entrega)
);

CREATE TABLE revisiones_entrega (
    id_revision_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_entrega integer NOT NULL,
    id_usuario_revisa integer NOT NULL,
    resultado_revision varchar(40) NOT NULL,
    observacion varchar(700),
    fecha_revision timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_revision varchar(30) NOT NULL DEFAULT 'REGISTRADA',
    CONSTRAINT pk_revisiones_entrega PRIMARY KEY (id_revision_entrega)
);

CREATE TABLE pagos (
    id_pago integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    monto_total numeric(10,2) NOT NULL,
    comision_plataforma numeric(10,2) NOT NULL DEFAULT 0,
    monto_estudiante numeric(10,2) NOT NULL,
    metodo_pago varchar(50) NOT NULL,
    estado_pago varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    referencia_externa varchar(150),
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_pago timestamp,
    fecha_liberacion timestamp,
    CONSTRAINT pk_pagos PRIMARY KEY (id_pago),
    CONSTRAINT uq_pagos_trabajo UNIQUE (id_trabajo),
    CONSTRAINT ck_pagos_montos CHECK (
        monto_total >= 0
        AND comision_plataforma >= 0
        AND monto_estudiante >= 0
    )
);

CREATE TABLE transacciones_pago (
    id_transaccion integer GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer NOT NULL,
    tipo_transaccion varchar(40) NOT NULL,
    monto numeric(10,2) NOT NULL,
    estado_transaccion varchar(30) NOT NULL,
    referencia_externa varchar(150),
    fecha_transaccion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observacion varchar(300),
    CONSTRAINT pk_transacciones_pago PRIMARY KEY (id_transaccion),
    CONSTRAINT ck_transacciones_pago_monto CHECK (monto >= 0)
);

CREATE TABLE conversaciones (
    id_conversacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_postulacion integer,
    id_trabajo integer,
    estado_conversacion varchar(30) NOT NULL DEFAULT 'ABIERTA',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultimo_mensaje timestamp,
    CONSTRAINT pk_conversaciones PRIMARY KEY (id_conversacion)
);

CREATE TABLE mensajes (
    id_mensaje integer GENERATED BY DEFAULT AS IDENTITY,
    id_conversacion integer NOT NULL,
    id_usuario_emisor integer NOT NULL,
    contenido text NOT NULL,
    fecha_envio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leido boolean NOT NULL DEFAULT false,
    fecha_lectura timestamp,
    CONSTRAINT pk_mensajes PRIMARY KEY (id_mensaje)
);

CREATE TABLE archivos_adjuntos (
    id_archivo integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer,
    id_entrega integer,
    id_mensaje integer,
    id_usuario_sube integer NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime varchar(100) NOT NULL,
    extension varchar(20),
    tamano_bytes bigint NOT NULL,
    contenido_archivo bytea NOT NULL,
    fecha_subida timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_archivo varchar(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT pk_archivos_adjuntos PRIMARY KEY (id_archivo),
    CONSTRAINT ck_archivos_adjuntos_tamano CHECK (tamano_bytes >= 0)
);

CREATE TABLE notificaciones (
    id_notificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo varchar(150) NOT NULL,
    mensaje varchar(500) NOT NULL,
    leida boolean NOT NULL DEFAULT false,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notificaciones PRIMARY KEY (id_notificacion)
);

CREATE TABLE portafolio (
    id_portafolio integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo varchar(150) NOT NULL,
    descripcion varchar(700),
    enlace_externo varchar(500),
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_portafolio varchar(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT pk_portafolio PRIMARY KEY (id_portafolio)
);

CREATE TABLE publicaciones (
    id_publicacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    contenido text NOT NULL,
    tipo_publicacion varchar(40) NOT NULL,
    fecha_publicacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_publicacion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_publicaciones PRIMARY KEY (id_publicacion)
);

CREATE TABLE recomendaciones (
    id_recomendacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_recomienda integer NOT NULL,
    id_usuario_recomendado integer NOT NULL,
    id_trabajo integer,
    comentario varchar(700) NOT NULL,
    fecha_recomendacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_recomendacion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_recomendaciones PRIMARY KEY (id_recomendacion)
);

CREATE TABLE calificaciones (
    id_calificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    id_calificador integer NOT NULL,
    id_calificado integer NOT NULL,
    puntuacion integer NOT NULL,
    comentario varchar(500),
    fecha_calificacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_calificaciones PRIMARY KEY (id_calificacion),
    CONSTRAINT ck_calificaciones_puntuacion CHECK (puntuacion BETWEEN 1 AND 5)
);

CREATE TABLE conexiones_usuarios (
    id_conexion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_solicitante integer NOT NULL,
    id_usuario_receptor integer NOT NULL,
    estado_conexion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    mensaje varchar(300),
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_respuesta timestamp,
    CONSTRAINT pk_conexiones_usuarios PRIMARY KEY (id_conexion),
    CONSTRAINT uq_conexiones_usuarios_solicitante_receptor UNIQUE (id_usuario_solicitante, id_usuario_receptor),
    CONSTRAINT ck_conexiones_usuarios_no_autoconexion CHECK (id_usuario_solicitante <> id_usuario_receptor)
);

CREATE TABLE sesiones_usuario (
    id_sesion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    token_hash varchar(255) NOT NULL,
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp NOT NULL,
    fecha_cierre timestamp,
    estado_sesion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_sesiones_usuario PRIMARY KEY (id_sesion)
);

CREATE TABLE tokens_recuperacion_password (
    id_token integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    token_hash varchar(255) NOT NULL,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp NOT NULL,
    usado boolean NOT NULL DEFAULT false,
    fecha_uso timestamp,
    CONSTRAINT pk_tokens_recuperacion_password PRIMARY KEY (id_token)
);

CREATE TABLE verificaciones_usuario (
    id_verificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    correo_institucional varchar(150) NOT NULL,
    codigo_verificacion varchar(20) NOT NULL,
    estado_verificacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_verificacion timestamp,
    fecha_expiracion timestamp,
    ultima_revalidacion timestamp,
    tipo_verificacion varchar(50) NOT NULL,
    observacion varchar(300),
    CONSTRAINT pk_verificaciones_usuario PRIMARY KEY (id_verificacion)
);

CREATE TABLE intentos_login (
    id_intento integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer,
    correo varchar(150) NOT NULL,
    exitoso boolean NOT NULL,
    motivo_fallo varchar(150),
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_intento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_intentos_login PRIMARY KEY (id_intento)
);

CREATE TABLE historial_estados (
    id_historial_estado integer GENERATED BY DEFAULT AS IDENTITY,
    entidad varchar(60) NOT NULL,
    id_entidad integer NOT NULL,
    estado_anterior varchar(40),
    estado_nuevo varchar(40) NOT NULL,
    id_usuario_cambio integer,
    motivo_cambio varchar(300),
    fecha_cambio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historial_estados PRIMARY KEY (id_historial_estado)
);

CREATE TABLE reportes (
    id_reporte integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_reporta integer NOT NULL,
    id_usuario_reportado integer,
    id_tarea integer,
    motivo varchar(150) NOT NULL,
    descripcion varchar(700),
    estado_reporte varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_reporte timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_trabajo integer,
    id_entrega integer,
    id_pago integer,
    tipo_reporte varchar(30) NOT NULL,
    categoria_reporte varchar(80) NOT NULL,
    CONSTRAINT pk_reportes PRIMARY KEY (id_reporte)
);

CREATE TABLE auditoria_sistema (
    id_auditoria integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer,
    accion varchar(100) NOT NULL,
    tabla_afectada varchar(100) NOT NULL,
    id_registro_afectado integer,
    datos_antes text,
    datos_despues text,
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_accion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditoria_sistema PRIMARY KEY (id_auditoria)
);

ALTER TABLE carreras
    ADD CONSTRAINT fk_carreras_universidades
    FOREIGN KEY (id_universidad) REFERENCES universidades (id_universidad);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios_universidades
    FOREIGN KEY (id_universidad) REFERENCES universidades (id_universidad);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_roles
    FOREIGN KEY (id_rol) REFERENCES roles (id_rol);

ALTER TABLE usuarios_estudiantes
    ADD CONSTRAINT fk_usuarios_estudiantes_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuarios_estudiantes
    ADD CONSTRAINT fk_usuarios_estudiantes_carreras
    FOREIGN KEY (id_carrera) REFERENCES carreras (id_carrera);

ALTER TABLE usuarios_habilidades
    ADD CONSTRAINT fk_usuarios_habilidades_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuarios_habilidades
    ADD CONSTRAINT fk_usuarios_habilidades_habilidades
    FOREIGN KEY (id_habilidad) REFERENCES habilidades (id_habilidad);

ALTER TABLE tareas
    ADD CONSTRAINT fk_tareas_categorias
    FOREIGN KEY (id_categoria) REFERENCES categorias_tarea (id_categoria);

ALTER TABLE tareas
    ADD CONSTRAINT fk_tareas_clientes
    FOREIGN KEY (id_cliente) REFERENCES usuarios (id_usuario);

ALTER TABLE tareas_habilidades
    ADD CONSTRAINT fk_tareas_habilidades_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE tareas_habilidades
    ADD CONSTRAINT fk_tareas_habilidades_habilidades
    FOREIGN KEY (id_habilidad) REFERENCES habilidades (id_habilidad);

ALTER TABLE postulaciones
    ADD CONSTRAINT fk_postulaciones_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE postulaciones
    ADD CONSTRAINT fk_postulaciones_usuarios_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE trabajos_asignados
    ADD CONSTRAINT fk_trabajos_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE trabajos_asignados
    ADD CONSTRAINT fk_trabajos_usuarios_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE entregas
    ADD CONSTRAINT fk_entregas_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE comentarios_entrega
    ADD CONSTRAINT fk_comentarios_entrega_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE comentarios_entrega
    ADD CONSTRAINT fk_comentarios_entrega_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE revisiones_entrega
    ADD CONSTRAINT fk_revisiones_entrega_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE revisiones_entrega
    ADD CONSTRAINT fk_revisiones_entrega_usuarios
    FOREIGN KEY (id_usuario_revisa) REFERENCES usuarios (id_usuario);

ALTER TABLE pagos
    ADD CONSTRAINT fk_pagos_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE transacciones_pago
    ADD CONSTRAINT fk_transacciones_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_postulaciones
    FOREIGN KEY (id_postulacion) REFERENCES postulaciones (id_postulacion);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE mensajes
    ADD CONSTRAINT fk_mensajes_conversaciones
    FOREIGN KEY (id_conversacion) REFERENCES conversaciones (id_conversacion);

ALTER TABLE mensajes
    ADD CONSTRAINT fk_mensajes_usuarios
    FOREIGN KEY (id_usuario_emisor) REFERENCES usuarios (id_usuario);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_mensajes
    FOREIGN KEY (id_mensaje) REFERENCES mensajes (id_mensaje);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_usuarios
    FOREIGN KEY (id_usuario_sube) REFERENCES usuarios (id_usuario);

ALTER TABLE notificaciones
    ADD CONSTRAINT fk_notificaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE portafolio
    ADD CONSTRAINT fk_portafolio_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE publicaciones
    ADD CONSTRAINT fk_publicaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_usuario_recomienda
    FOREIGN KEY (id_usuario_recomienda) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_usuario_recomendado
    FOREIGN KEY (id_usuario_recomendado) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_calificador
    FOREIGN KEY (id_calificador) REFERENCES usuarios (id_usuario);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_calificado
    FOREIGN KEY (id_calificado) REFERENCES usuarios (id_usuario);

ALTER TABLE conexiones_usuarios
    ADD CONSTRAINT fk_conexiones_usuarios_solicitante
    FOREIGN KEY (id_usuario_solicitante) REFERENCES usuarios (id_usuario);

ALTER TABLE conexiones_usuarios
    ADD CONSTRAINT fk_conexiones_usuarios_receptor
    FOREIGN KEY (id_usuario_receptor) REFERENCES usuarios (id_usuario);

ALTER TABLE sesiones_usuario
    ADD CONSTRAINT fk_sesiones_usuario_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE tokens_recuperacion_password
    ADD CONSTRAINT fk_tokens_recuperacion_password_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE verificaciones_usuario
    ADD CONSTRAINT fk_verificaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE intentos_login
    ADD CONSTRAINT fk_intentos_login_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE historial_estados
    ADD CONSTRAINT fk_historial_estados_usuarios
    FOREIGN KEY (id_usuario_cambio) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_usuario_reporta
    FOREIGN KEY (id_usuario_reporta) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_usuario_reportado
    FOREIGN KEY (id_usuario_reportado) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE auditoria_sistema
    ADD CONSTRAINT fk_auditoria_sistema_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

CREATE INDEX idx_tareas_estado ON tareas (estado_tarea);
CREATE INDEX idx_tareas_categoria ON tareas (id_categoria);
CREATE INDEX idx_tareas_cliente ON tareas (id_cliente);
CREATE INDEX idx_tareas_coordenadas ON tareas (latitud, longitud)
    WHERE latitud IS NOT NULL AND longitud IS NOT NULL;
CREATE INDEX idx_postulaciones_estudiante ON postulaciones (id_estudiante);
CREATE INDEX idx_postulaciones_estado ON postulaciones (estado_postulacion);
CREATE INDEX idx_trabajos_estudiante ON trabajos_asignados (id_estudiante);
CREATE INDEX idx_entregas_trabajo ON entregas (id_trabajo);
CREATE INDEX idx_pagos_estado ON pagos (estado_pago);
CREATE INDEX idx_notificaciones_usuario ON notificaciones (id_usuario);
CREATE INDEX idx_mensajes_conversacion ON mensajes (id_conversacion);
CREATE INDEX idx_reportes_estado ON reportes (estado_reporte);

INSERT INTO roles (id_rol, nombre_rol) VALUES
    (1, 'ADMIN'),
    (2, 'ESTUDIANTE'),
    (3, 'CLIENTE')
ON CONFLICT (id_rol) DO NOTHING;

INSERT INTO universidades (id_universidad, nombre_universidad, dominio_correo, estado) VALUES
    (1, 'Universidad Demo', 'unidemo.edu', true)
ON CONFLICT (id_universidad) DO NOTHING;

INSERT INTO carreras (id_carrera, nombre_carrera, id_universidad) VALUES
    (1, 'Ingenieria en Sistemas', 1),
    (2, 'Diseno Grafico', 1),
    (3, 'Administracion de Empresas', 1)
ON CONFLICT (id_carrera) DO NOTHING;

INSERT INTO categorias_tarea (id_categoria, nombre_categoria, descripcion, estado) VALUES
    (1, 'Tutoria', 'Apoyo academico por horas o sesiones.', true),
    (2, 'Desarrollo de software', 'Aplicaciones, sitios web, scripts y soporte tecnico.', true),
    (3, 'Diseno', 'Diseno grafico, UI, presentaciones y piezas digitales.', true),
    (4, 'Eventos', 'Apoyo logistico, voluntariado y actividades universitarias.', true)
ON CONFLICT (id_categoria) DO NOTHING;

INSERT INTO habilidades (id_habilidad, nombre_habilidad, descripcion, estado) VALUES
    (1, 'Kotlin', 'Desarrollo de aplicaciones Android.', true),
    (2, 'Java', 'Desarrollo backend y aplicaciones orientadas a objetos.', true),
    (3, 'Spring Boot', 'Creacion de APIs REST.', true),
    (4, 'PostgreSQL', 'Modelado y consultas de base de datos.', true),
    (5, 'Figma', 'Diseno de interfaces y prototipado.', true)
ON CONFLICT (id_habilidad) DO NOTHING;

INSERT INTO usuarios (
    id_usuario,
    nombre,
    apellido,
    correo,
    password_hash,
    fecha_registro,
    estado_usuario,
    id_universidad
) VALUES
    (1, 'Cliente', 'Demo', 'cliente.demo@unidemo.edu', 'demo-password-hash', CURRENT_TIMESTAMP, 'ACTIVO', 1),
    (2, 'Estudiante', 'Demo', 'estudiante.demo@unidemo.edu', 'demo-password-hash', CURRENT_TIMESTAMP, 'ACTIVO', 1)
ON CONFLICT (id_usuario) DO NOTHING;

INSERT INTO usuario_roles (id_usuario, id_rol) VALUES
    (1, 3),
    (2, 2)
ON CONFLICT (id_usuario, id_rol) DO NOTHING;

INSERT INTO usuarios_estudiantes (
    id_usuario,
    id_carrera,
    carnet_universitario,
    estado_perfil_estudiante,
    fecha_creacion
) VALUES
    (2, 1, '2026-0001', 'ACTIVO', CURRENT_TIMESTAMP)
ON CONFLICT (id_usuario) DO NOTHING;

ALTER TABLE roles ALTER COLUMN id_rol RESTART WITH 4;
ALTER TABLE universidades ALTER COLUMN id_universidad RESTART WITH 2;
ALTER TABLE carreras ALTER COLUMN id_carrera RESTART WITH 4;
ALTER TABLE categorias_tarea ALTER COLUMN id_categoria RESTART WITH 5;
ALTER TABLE habilidades ALTER COLUMN id_habilidad RESTART WITH 6;
ALTER TABLE usuarios ALTER COLUMN id_usuario RESTART WITH 3;

COMMIT;
