-- T4KASH - Esquema PostgreSQL
-- Modelo principal de datos para desarrollo, pruebas y despliegue.
-- Ejecutar despues de crear la base de datos:
--   CREATE DATABASE t4kash;
--   psql -U postgres -d t4kash -f schema-postgresql.sql

BEGIN;

DROP TABLE IF EXISTS archivos_adjuntos CASCADE;
DROP TABLE IF EXISTS apelaciones_sancion CASCADE;
DROP TABLE IF EXISTS auditoria_sistema CASCADE;
DROP TABLE IF EXISTS calificaciones CASCADE;
DROP TABLE IF EXISTS canjes_puntos CASCADE;
DROP TABLE IF EXISTS catalogo_beneficios_puntos CASCADE;
DROP TABLE IF EXISTS comentarios_entrega CASCADE;
DROP TABLE IF EXISTS comentarios_publicacion CASCADE;
DROP TABLE IF EXISTS conexiones_usuarios CASCADE;
DROP TABLE IF EXISTS conversaciones CASCADE;
DROP TABLE IF EXISTS desembolsos_pago CASCADE;
DROP TABLE IF EXISTS eventos_disputa_pago CASCADE;
DROP TABLE IF EXISTS eventos_webhook_pago CASCADE;
DROP TABLE IF EXISTS entregas CASCADE;
DROP TABLE IF EXISTS historial_estados CASCADE;
DROP TABLE IF EXISTS historial_nombres_usuario CASCADE;
DROP TABLE IF EXISTS intentos_login CASCADE;
DROP TABLE IF EXISTS eventos_webhook_identidad CASCADE;
DROP TABLE IF EXISTS verificaciones_identidad CASCADE;
DROP TABLE IF EXISTS mensajes CASCADE;
DROP TABLE IF EXISTS metodos_cobro_usuario CASCADE;
DROP TABLE IF EXISTS movimientos_puntos CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS pagos CASCADE;
DROP TABLE IF EXISTS portafolio CASCADE;
DROP TABLE IF EXISTS postulaciones CASCADE;
DROP TABLE IF EXISTS publicaciones_guardadas CASCADE;
DROP TABLE IF EXISTS publicaciones_ocultas CASCADE;
DROP TABLE IF EXISTS reacciones_publicacion CASCADE;
DROP TABLE IF EXISTS publicaciones CASCADE;
DROP TABLE IF EXISTS recomendaciones CASCADE;
DROP TABLE IF EXISTS reportes CASCADE;
DROP TABLE IF EXISTS reembolsos_pago CASCADE;
DROP TABLE IF EXISTS revisiones_entrega CASCADE;
DROP TABLE IF EXISTS sesiones_usuario CASCADE;
DROP TABLE IF EXISTS sanciones_usuario CASCADE;
DROP TABLE IF EXISTS tareas_habilidades CASCADE;
DROP TABLE IF EXISTS tokens_recuperacion_password CASCADE;
DROP TABLE IF EXISTS trabajos_asignados CASCADE;
DROP TABLE IF EXISTS transacciones_pago CASCADE;
DROP TABLE IF EXISTS disputas_pago CASCADE;
DROP TABLE IF EXISTS bloqueos_usuarios CASCADE;
DROP TABLE IF EXISTS usuario_roles CASCADE;
DROP TABLE IF EXISTS usuarios_estudiantes CASCADE;
DROP TABLE IF EXISTS usuarios_habilidades CASCADE;
DROP TABLE IF EXISTS verificaciones_usuario CASCADE;
DROP TABLE IF EXISTS tareas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS carreras CASCADE;
DROP TABLE IF EXISTS dominios_universidad CASCADE;
DROP TABLE IF EXISTS universidades CASCADE;
DROP TABLE IF EXISTS categorias_tarea CASCADE;
DROP TABLE IF EXISTS habilidades CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE universidades (
    id_universidad integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_universidad varchar(150) NOT NULL,
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_universidades PRIMARY KEY (id_universidad)
);

CREATE TABLE dominios_universidad (
    id_dominio integer GENERATED BY DEFAULT AS IDENTITY,
    id_universidad integer NOT NULL,
    dominio_correo varchar(100) NOT NULL,
    tipo_dominio varchar(30) NOT NULL DEFAULT 'INSTITUCIONAL',
    verificacion_automatica boolean NOT NULL DEFAULT false,
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_dominios_universidad PRIMARY KEY (id_dominio),
    CONSTRAINT uq_dominios_universidad_correo UNIQUE (dominio_correo),
    CONSTRAINT ck_dominios_universidad_formato CHECK (
        dominio_correo = lower(dominio_correo)
        AND dominio_correo ~ '^[a-z0-9][a-z0-9.-]*\.[a-z]{2,}$'
    ),
    CONSTRAINT ck_dominios_universidad_tipo CHECK (
        tipo_dominio IN ('ESTUDIANTIL', 'INSTITUCIONAL', 'GENERAL')
    )
);

CREATE TABLE carreras (
    id_carrera integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_carrera varchar(120) NOT NULL,
    id_universidad integer NOT NULL,
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_carreras PRIMARY KEY (id_carrera),
    CONSTRAINT uq_carreras_universidad_nombre UNIQUE (id_universidad, nombre_carrera)
);

CREATE TABLE roles (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_rol varchar(50) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_rol),
    CONSTRAINT uq_roles_nombre_rol UNIQUE (nombre_rol)
);

CREATE TABLE usuarios (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    uuid_publico uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre_usuario varchar(30) NOT NULL,
    nombre varchar(80) NOT NULL,
    apellido varchar(80) NOT NULL,
    correo varchar(150) NOT NULL,
    password_hash varchar(255) NOT NULL,
    telefono varchar(25),
    direccion varchar(150),
    fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_usuario varchar(30) NOT NULL DEFAULT 'ACTIVO',
    id_universidad integer,
    -- Token FCM del dispositivo activo para notificaciones push. Si esta
    -- columna se agrega a una base ya desplegada, usar:
    --   ALTER TABLE usuarios ADD COLUMN fcm_token varchar(255);
    fcm_token varchar(255),
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_uuid_publico UNIQUE (uuid_publico),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo),
    CONSTRAINT ck_usuarios_nombre_usuario CHECK (
        nombre_usuario ~ '^[a-z0-9][a-z0-9._]{2,29}$'
    )
);

CREATE TABLE usuario_roles (
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    CONSTRAINT pk_usuario_roles PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE usuarios_estudiantes (
    id_usuario integer NOT NULL,
    id_carrera integer,
    carnet_universitario varchar(50),
    estado_perfil_estudiante varchar(30) NOT NULL DEFAULT 'INCOMPLETO',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_estudiantes PRIMARY KEY (id_usuario)
);

CREATE TABLE habilidades (
    id_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_habilidad varchar(100) NOT NULL,
    descripcion varchar(250),
    estado boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_habilidades PRIMARY KEY (id_habilidad),
    CONSTRAINT uq_habilidades_nombre_habilidad UNIQUE (nombre_habilidad)
);

CREATE TABLE usuarios_habilidades (
    id_usuario_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_habilidad integer NOT NULL,
    nivel varchar(30) NOT NULL,
    descripcion varchar(250),
    verificada boolean NOT NULL DEFAULT false,
    fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_habilidades PRIMARY KEY (id_usuario_habilidad),
    CONSTRAINT uq_usuarios_habilidades_usuario_habilidad UNIQUE (id_usuario, id_habilidad)
);

CREATE TABLE categorias_tarea (
    id_categoria integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria varchar(100) NOT NULL,
    descripcion varchar(250),
    estado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_categorias_tarea PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categorias_tarea_nombre_categoria UNIQUE (nombre_categoria)
);

CREATE TABLE tareas (
    id_tarea integer GENERATED BY DEFAULT AS IDENTITY,
    titulo varchar(150) NOT NULL,
    descripcion text NOT NULL,
    presupuesto numeric(10,2) NOT NULL,
    fecha_publicacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_limite_postulacion timestamp,
    fecha_limite timestamp,
    estado_tarea varchar(30) NOT NULL DEFAULT 'PUBLICADA',
    id_categoria integer NOT NULL,
    id_cliente integer NOT NULL,
    tipo_oportunidad varchar(50) NOT NULL,
    modalidad varchar(30),
    visibilidad varchar(30) NOT NULL DEFAULT 'PUBLICA',
    direccion_referencia varchar(250),
    latitud numeric(9,6),
    longitud numeric(9,6),
    CONSTRAINT pk_tareas PRIMARY KEY (id_tarea),
    CONSTRAINT ck_tareas_presupuesto CHECK (presupuesto >= 0),
    CONSTRAINT ck_tareas_coordenadas_validas CHECK (
        (latitud IS NULL AND longitud IS NULL)
        OR (
            latitud IS NOT NULL
            AND longitud IS NOT NULL
            AND latitud BETWEEN -90 AND 90
            AND longitud BETWEEN -180 AND 180
        )
    )
);

CREATE TABLE tareas_habilidades (
    id_tarea_habilidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_habilidad integer NOT NULL,
    es_requerida boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tareas_habilidades PRIMARY KEY (id_tarea_habilidad),
    CONSTRAINT uq_tareas_habilidades_tarea_habilidad UNIQUE (id_tarea, id_habilidad)
);

CREATE TABLE postulaciones (
    id_postulacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_estudiante integer NOT NULL,
    mensaje varchar(500),
    precio_propuesto numeric(10,2),
    fecha_postulacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_postulacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    numero_intento integer NOT NULL DEFAULT 1,
    CONSTRAINT pk_postulaciones PRIMARY KEY (id_postulacion),
    CONSTRAINT uq_postulaciones_tarea_estudiante_intento
        UNIQUE (id_tarea, id_estudiante, numero_intento),
    CONSTRAINT ck_postulaciones_numero_intento CHECK (numero_intento BETWEEN 1 AND 3),
    CONSTRAINT ck_postulaciones_precio CHECK (precio_propuesto IS NULL OR precio_propuesto >= 0)
);

CREATE TABLE trabajos_asignados (
    id_trabajo integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_estudiante integer NOT NULL,
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_entrega_esperada timestamp,
    estado_trabajo varchar(30) NOT NULL DEFAULT 'EN_PROCESO',
    CONSTRAINT pk_trabajos_asignados PRIMARY KEY (id_trabajo),
    CONSTRAINT uq_trabajos_asignados_tarea UNIQUE (id_tarea)
);

CREATE TABLE entregas (
    id_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    descripcion_entrega text NOT NULL,
    fecha_entrega timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_entrega varchar(30) NOT NULL DEFAULT 'ENVIADA',
    CONSTRAINT pk_entregas PRIMARY KEY (id_entrega)
);

CREATE TABLE comentarios_entrega (
    id_comentario_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_entrega integer NOT NULL,
    id_usuario integer NOT NULL,
    comentario varchar(700) NOT NULL,
    tipo_comentario varchar(40) NOT NULL,
    fecha_comentario timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comentarios_entrega PRIMARY KEY (id_comentario_entrega)
);

CREATE TABLE revisiones_entrega (
    id_revision_entrega integer GENERATED BY DEFAULT AS IDENTITY,
    id_entrega integer NOT NULL,
    id_usuario_revisa integer NOT NULL,
    resultado_revision varchar(40) NOT NULL,
    observacion varchar(700),
    fecha_revision timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_revision varchar(30) NOT NULL DEFAULT 'REGISTRADA',
    CONSTRAINT pk_revisiones_entrega PRIMARY KEY (id_revision_entrega)
);

CREATE TABLE pagos (
    id_pago integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    id_cliente integer NOT NULL,
    id_estudiante integer NOT NULL,
    uuid_pago uuid NOT NULL DEFAULT gen_random_uuid(),
    proveedor_pago varchar(30) NOT NULL DEFAULT 'PAGADITO',
    entorno_pago varchar(20) NOT NULL DEFAULT 'SANDBOX',
    metodo_pago varchar(30) NOT NULL DEFAULT 'PAGADITO',
    moneda_cobro char(3) NOT NULL DEFAULT 'NIO',
    moneda_procesamiento char(3),
    tipo_cambio numeric(18,8),
    monto_procesamiento numeric(12,2),
    monto_estudiante numeric(12,2) NOT NULL,
    porcentaje_comision_plataforma numeric(5,2) NOT NULL DEFAULT 15.00,
    comision_plataforma numeric(12,2) NOT NULL DEFAULT 0,
    comision_cliente numeric(12,2) NOT NULL DEFAULT 0,
    comision_estudiante numeric(12,2) NOT NULL DEFAULT 0,
    comision_procesador numeric(12,2) NOT NULL DEFAULT 0,
    impuesto_procesador numeric(12,2) NOT NULL DEFAULT 0,
    monto_total_cliente numeric(12,2) NOT NULL,
    estado_pago varchar(40) NOT NULL DEFAULT 'PENDIENTE_PAGO',
    referencia_comercio varchar(100),
    referencia_proveedor varchar(150),
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp,
    fecha_confirmacion timestamp,
    fecha_liberacion timestamp,
    fecha_reembolso timestamp,
    CONSTRAINT pk_pagos PRIMARY KEY (id_pago),
    CONSTRAINT uq_pagos_uuid UNIQUE (uuid_pago),
    CONSTRAINT uq_pagos_trabajo UNIQUE (id_trabajo),
    CONSTRAINT uq_pagos_referencia_comercio UNIQUE (referencia_comercio),
    CONSTRAINT ck_pagos_montos CHECK (
        monto_estudiante >= 0
        AND porcentaje_comision_plataforma BETWEEN 0 AND 100
        AND comision_plataforma >= 0
        AND comision_cliente >= 0
        AND comision_estudiante >= 0
        AND comision_plataforma = comision_cliente + comision_estudiante
        AND comision_procesador >= 0
        AND impuesto_procesador >= 0
        AND monto_total_cliente = monto_estudiante
            + comision_plataforma
            + comision_procesador
            + impuesto_procesador
        AND (monto_procesamiento IS NULL OR monto_procesamiento >= 0)
        AND (tipo_cambio IS NULL OR tipo_cambio > 0)
    ),
    CONSTRAINT ck_pagos_moneda_cobro CHECK (moneda_cobro ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_pagos_moneda_procesamiento CHECK (
        moneda_procesamiento IS NULL OR moneda_procesamiento ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT ck_pagos_proveedor CHECK (proveedor_pago IN ('PAGADITO', 'EXTERNO')),
    CONSTRAINT ck_pagos_entorno CHECK (entorno_pago IN ('SANDBOX', 'PRODUCCION', 'EXTERNO')),
    CONSTRAINT ck_pagos_metodo CHECK (metodo_pago IN ('PAGADITO', 'EFECTIVO')),
    CONSTRAINT ck_pagos_efectivo CHECK (
        metodo_pago <> 'EFECTIVO'
        OR (
            proveedor_pago = 'EXTERNO'
            AND entorno_pago = 'EXTERNO'
            AND porcentaje_comision_plataforma = 0
            AND comision_plataforma = 0
            AND comision_procesador = 0
            AND impuesto_procesador = 0
            AND moneda_procesamiento IS NULL
            AND monto_procesamiento IS NULL
        )
    ),
    CONSTRAINT ck_pagos_pagadito CHECK (
        metodo_pago <> 'PAGADITO'
        OR (
            proveedor_pago = 'PAGADITO'
            AND entorno_pago IN ('SANDBOX', 'PRODUCCION')
        )
    )
);

CREATE TABLE historial_nombres_usuario (
    id_historial_nombre integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    nombre_anterior varchar(30),
    nombre_nuevo varchar(30) NOT NULL,
    fecha_cambio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo varchar(200),
    CONSTRAINT pk_historial_nombres_usuario PRIMARY KEY (id_historial_nombre),
    CONSTRAINT ck_historial_nombres_usuario_formato CHECK (
        nombre_nuevo ~ '^[a-z0-9][a-z0-9._]{2,29}$'
    )
);

CREATE TABLE metodos_cobro_usuario (
    id_metodo_cobro integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    proveedor varchar(30) NOT NULL,
    alias_metodo varchar(80) NOT NULL,
    referencia_tokenizada varchar(255) NOT NULL,
    ultimos_cuatro varchar(4),
    moneda char(3) NOT NULL DEFAULT 'NIO',
    predeterminado boolean NOT NULL DEFAULT false,
    verificado boolean NOT NULL DEFAULT false,
    estado_metodo varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_verificacion timestamp,
    fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_metodos_cobro_usuario PRIMARY KEY (id_metodo_cobro),
    CONSTRAINT uq_metodos_cobro_referencia UNIQUE (proveedor, referencia_tokenizada),
    CONSTRAINT ck_metodos_cobro_moneda CHECK (moneda ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_metodos_cobro_ultimos_cuatro CHECK (
        ultimos_cuatro IS NULL OR ultimos_cuatro ~ '^[0-9]{4}$'
    )
);

CREATE TABLE transacciones_pago (
    id_transaccion bigint GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer NOT NULL,
    id_usuario integer,
    tipo_movimiento varchar(40) NOT NULL,
    saldo_afectado varchar(30) NOT NULL,
    monto numeric(12,2) NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'NIO',
    estado_movimiento varchar(30) NOT NULL DEFAULT 'REGISTRADO',
    proveedor_pago varchar(30) NOT NULL,
    clave_idempotencia varchar(150) NOT NULL,
    referencia_proveedor varchar(150),
    fecha_evento_proveedor timestamp,
    fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descripcion varchar(300),
    metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_transacciones_pago PRIMARY KEY (id_transaccion),
    CONSTRAINT uq_transacciones_pago_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_transacciones_pago_monto CHECK (monto >= 0),
    CONSTRAINT ck_transacciones_pago_moneda CHECK (moneda ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_transacciones_pago_saldo CHECK (
        saldo_afectado IN ('PENDIENTE', 'RETENIDO', 'DISPONIBLE', 'EXTERNO', 'NINGUNO')
    )
);

CREATE TABLE eventos_webhook_pago (
    id_evento_webhook bigint GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer,
    proveedor_pago varchar(30) NOT NULL,
    entorno_pago varchar(20) NOT NULL,
    id_evento_proveedor varchar(180) NOT NULL,
    tipo_evento varchar(80) NOT NULL,
    firma_valida boolean NOT NULL DEFAULT false,
    payload jsonb NOT NULL,
    estado_procesamiento varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    intentos_procesamiento integer NOT NULL DEFAULT 0,
    fecha_recepcion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesamiento timestamp,
    ultimo_error varchar(700),
    CONSTRAINT pk_eventos_webhook_pago PRIMARY KEY (id_evento_webhook),
    CONSTRAINT uq_eventos_webhook_pago_proveedor
        UNIQUE (proveedor_pago, entorno_pago, id_evento_proveedor),
    CONSTRAINT ck_eventos_webhook_pago_intentos CHECK (intentos_procesamiento >= 0),
    CONSTRAINT ck_eventos_webhook_pago_entorno CHECK (
        entorno_pago IN ('SANDBOX', 'PRODUCCION')
    )
);

CREATE TABLE disputas_pago (
    id_disputa integer GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer NOT NULL,
    id_usuario_abre integer NOT NULL,
    id_admin_asignado integer,
    motivo varchar(120) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    solucion_solicitada varchar(40) NOT NULL,
    monto_disputado numeric(12,2) NOT NULL,
    estado_disputa varchar(30) NOT NULL DEFAULT 'ABIERTA',
    prioridad varchar(20) NOT NULL DEFAULT 'NORMAL',
    fecha_apertura timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_limite_respuesta timestamp,
    fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_resolucion timestamp,
    resolucion varchar(1000),
    CONSTRAINT pk_disputas_pago PRIMARY KEY (id_disputa),
    CONSTRAINT ck_disputas_pago_monto CHECK (monto_disputado >= 0),
    CONSTRAINT ck_disputas_pago_prioridad CHECK (
        prioridad IN ('BAJA', 'NORMAL', 'ALTA', 'CRITICA')
    )
);

CREATE TABLE eventos_disputa_pago (
    id_evento_disputa bigint GENERATED BY DEFAULT AS IDENTITY,
    id_disputa integer NOT NULL,
    id_usuario integer,
    tipo_evento varchar(50) NOT NULL,
    estado_anterior varchar(30),
    estado_nuevo varchar(30),
    detalle varchar(1000),
    fecha_evento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_eventos_disputa_pago PRIMARY KEY (id_evento_disputa)
);

CREATE TABLE reembolsos_pago (
    id_reembolso integer GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer NOT NULL,
    id_disputa integer,
    id_usuario_solicita integer,
    monto_reembolso numeric(12,2) NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'NIO',
    motivo varchar(500) NOT NULL,
    estado_reembolso varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    clave_idempotencia varchar(150) NOT NULL,
    referencia_proveedor varchar(150),
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesamiento timestamp,
    fecha_confirmacion timestamp,
    ultimo_error varchar(700),
    CONSTRAINT pk_reembolsos_pago PRIMARY KEY (id_reembolso),
    CONSTRAINT uq_reembolsos_pago_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_reembolsos_pago_monto CHECK (monto_reembolso > 0),
    CONSTRAINT ck_reembolsos_pago_moneda CHECK (moneda ~ '^[A-Z]{3}$')
);

CREATE TABLE desembolsos_pago (
    id_desembolso integer GENERATED BY DEFAULT AS IDENTITY,
    id_pago integer NOT NULL,
    id_estudiante integer NOT NULL,
    id_metodo_cobro integer,
    monto_desembolso numeric(12,2) NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'NIO',
    proveedor_desembolso varchar(30) NOT NULL DEFAULT 'SANDBOX',
    estado_desembolso varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    clave_idempotencia varchar(150) NOT NULL,
    referencia_destino varchar(100),
    referencia_proveedor varchar(150),
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesamiento timestamp,
    fecha_confirmacion timestamp,
    ultimo_error varchar(700),
    CONSTRAINT pk_desembolsos_pago PRIMARY KEY (id_desembolso),
    CONSTRAINT uq_desembolsos_pago_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_desembolsos_pago_monto CHECK (monto_desembolso > 0),
    CONSTRAINT ck_desembolsos_pago_moneda CHECK (moneda ~ '^[A-Z]{3}$')
);

CREATE TABLE catalogo_beneficios_puntos (
    id_beneficio integer GENERATED BY DEFAULT AS IDENTITY,
    codigo_beneficio varchar(50) NOT NULL,
    nombre_beneficio varchar(100) NOT NULL,
    descripcion varchar(400) NOT NULL,
    costo_puntos integer NOT NULL,
    duracion_horas integer,
    tipo_destino varchar(30) NOT NULL,
    estado_beneficio varchar(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_catalogo_beneficios_puntos PRIMARY KEY (id_beneficio),
    CONSTRAINT uq_catalogo_beneficios_puntos_codigo UNIQUE (codigo_beneficio),
    CONSTRAINT ck_catalogo_beneficios_puntos_costo CHECK (costo_puntos > 0),
    CONSTRAINT ck_catalogo_beneficios_puntos_duracion CHECK (
        duracion_horas IS NULL OR duracion_horas > 0
    ),
    CONSTRAINT ck_catalogo_beneficios_puntos_destino CHECK (
        tipo_destino IN ('TAREA', 'PUBLICACION', 'PERFIL')
    )
);

CREATE TABLE canjes_puntos (
    id_canje integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_beneficio integer NOT NULL,
    id_tarea integer,
    id_publicacion integer,
    puntos_utilizados integer NOT NULL,
    estado_canje varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    clave_idempotencia varchar(150) NOT NULL,
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_activacion timestamp,
    fecha_expiracion timestamp,
    fecha_cancelacion timestamp,
    CONSTRAINT pk_canjes_puntos PRIMARY KEY (id_canje),
    CONSTRAINT uq_canjes_puntos_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_canjes_puntos_cantidad CHECK (puntos_utilizados > 0),
    CONSTRAINT ck_canjes_puntos_destino CHECK (
        num_nonnulls(id_tarea, id_publicacion) <= 1
    )
);

CREATE TABLE movimientos_puntos (
    id_movimiento_puntos bigint GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_trabajo integer,
    id_canje integer,
    tipo_movimiento varchar(40) NOT NULL,
    direccion varchar(10) NOT NULL,
    cantidad integer NOT NULL,
    motivo varchar(300) NOT NULL,
    clave_idempotencia varchar(150) NOT NULL,
    estado_movimiento varchar(30) NOT NULL DEFAULT 'APLICADO',
    fecha_movimiento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp,
    CONSTRAINT pk_movimientos_puntos PRIMARY KEY (id_movimiento_puntos),
    CONSTRAINT uq_movimientos_puntos_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_movimientos_puntos_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_movimientos_puntos_direccion CHECK (direccion IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT ck_movimientos_puntos_origen CHECK (
        num_nonnulls(id_trabajo, id_canje) <= 1
    )
);

CREATE TABLE conversaciones (
    id_conversacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer NOT NULL,
    id_postulacion integer,
    id_trabajo integer,
    estado_conversacion varchar(30) NOT NULL DEFAULT 'ABIERTA',
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultimo_mensaje timestamp,
    CONSTRAINT pk_conversaciones PRIMARY KEY (id_conversacion)
);

CREATE TABLE mensajes (
    id_mensaje integer GENERATED BY DEFAULT AS IDENTITY,
    id_conversacion integer NOT NULL,
    id_usuario_emisor integer NOT NULL,
    contenido text NOT NULL,
    fecha_envio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leido boolean NOT NULL DEFAULT false,
    fecha_lectura timestamp,
    CONSTRAINT pk_mensajes PRIMARY KEY (id_mensaje)
);

CREATE TABLE archivos_adjuntos (
    id_archivo integer GENERATED BY DEFAULT AS IDENTITY,
    id_tarea integer,
    id_entrega integer,
    id_mensaje integer,
    id_publicacion integer,
    id_comentario_publicacion integer,
    id_verificacion integer,
    id_disputa integer,
    id_apelacion integer,
    id_usuario_sube integer NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime varchar(100) NOT NULL,
    extension varchar(20),
    tamano_bytes bigint NOT NULL,
    bucket_storage varchar(100) NOT NULL,
    ruta_storage varchar(500) NOT NULL,
    proveedor_storage varchar(30) NOT NULL DEFAULT 'SUPABASE',
    hash_sha256 char(64),
    visibilidad varchar(20) NOT NULL DEFAULT 'PRIVADO',
    fecha_subida timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion timestamp,
    estado_archivo varchar(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT pk_archivos_adjuntos PRIMARY KEY (id_archivo),
    CONSTRAINT ck_archivos_adjuntos_tamano CHECK (
        tamano_bytes BETWEEN 0 AND 104857600
    ),
    CONSTRAINT ck_archivos_adjuntos_destino CHECK (
        num_nonnulls(
            id_tarea,
            id_entrega,
            id_mensaje,
            id_publicacion,
            id_comentario_publicacion,
            id_verificacion,
            id_disputa,
            id_apelacion
        ) = 1
    ),
    CONSTRAINT ck_archivos_adjuntos_proveedor CHECK (
        proveedor_storage IN ('SUPABASE', 'CLOUDFLARE_R2')
    ),
    CONSTRAINT ck_archivos_adjuntos_hash CHECK (
        hash_sha256 IS NULL OR hash_sha256 ~ '^[a-f0-9]{64}$'
    ),
    CONSTRAINT ck_archivos_adjuntos_visibilidad CHECK (
        visibilidad IN ('PRIVADO', 'PUBLICO')
    )
);

CREATE TABLE notificaciones (
    id_notificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo varchar(150) NOT NULL,
    mensaje varchar(500) NOT NULL,
    leida boolean NOT NULL DEFAULT false,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notificaciones PRIMARY KEY (id_notificacion)
);

CREATE TABLE portafolio (
    id_portafolio integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    titulo varchar(150) NOT NULL,
    descripcion varchar(700),
    enlace_externo varchar(500),
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_portafolio varchar(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT pk_portafolio PRIMARY KEY (id_portafolio)
);

CREATE TABLE publicaciones (
    id_publicacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_publicacion_origen integer,
    contenido text,
    tipo_publicacion varchar(40) NOT NULL,
    visibilidad varchar(30) NOT NULL DEFAULT 'PUBLICA',
    permite_comentarios boolean NOT NULL DEFAULT true,
    fecha_publicacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_edicion timestamp,
    estado_publicacion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_publicaciones PRIMARY KEY (id_publicacion),
    CONSTRAINT ck_publicaciones_contenido CHECK (
        (
            contenido IS NOT NULL
            AND char_length(btrim(contenido)) BETWEEN 1 AND 5000
        )
        OR tipo_publicacion IN ('IMAGEN', 'VIDEO')
        OR id_publicacion_origen IS NOT NULL
    ),
    CONSTRAINT ck_publicaciones_tipo CHECK (
        tipo_publicacion IN (
            'TEXTO', 'IMAGEN', 'VIDEO', 'PROYECTO', 'LOGRO',
            'PREGUNTA', 'RECURSO', 'EVENTO', 'COMPARTIDA'
        )
    ),
    CONSTRAINT ck_publicaciones_visibilidad CHECK (
        visibilidad IN ('PUBLICA', 'CONEXIONES', 'UNIVERSIDAD')
    ),
    CONSTRAINT ck_publicaciones_estado CHECK (
        estado_publicacion IN ('ACTIVA', 'OCULTA', 'RETIRADA', 'ELIMINADA')
    ),
    CONSTRAINT ck_publicaciones_origen_distinto CHECK (
        id_publicacion_origen IS NULL
        OR id_publicacion_origen <> id_publicacion
    ),
    CONSTRAINT ck_publicaciones_compartida_origen CHECK (
        tipo_publicacion <> 'COMPARTIDA'
        OR id_publicacion_origen IS NOT NULL
    )
);

CREATE TABLE comentarios_publicacion (
    id_comentario_publicacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_publicacion integer NOT NULL,
    id_usuario integer NOT NULL,
    id_comentario_padre integer,
    contenido text NOT NULL,
    fecha_comentario timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_edicion timestamp,
    estado_comentario varchar(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT pk_comentarios_publicacion PRIMARY KEY (id_comentario_publicacion),
    CONSTRAINT uq_comentarios_publicacion_publicacion_id UNIQUE (
        id_publicacion,
        id_comentario_publicacion
    ),
    CONSTRAINT ck_comentarios_publicacion_contenido CHECK (
        char_length(btrim(contenido)) BETWEEN 1 AND 2000
    ),
    CONSTRAINT ck_comentarios_publicacion_estado CHECK (
        estado_comentario IN ('ACTIVO', 'OCULTO', 'RETIRADO', 'ELIMINADO')
    ),
    CONSTRAINT ck_comentarios_publicacion_padre_distinto CHECK (
        id_comentario_padre IS NULL
        OR id_comentario_padre <> id_comentario_publicacion
    )
);

CREATE TABLE reacciones_publicacion (
    id_reaccion integer GENERATED BY DEFAULT AS IDENTITY,
    id_publicacion integer NOT NULL,
    id_usuario integer NOT NULL,
    tipo_reaccion varchar(30) NOT NULL DEFAULT 'ME_GUSTA',
    fecha_reaccion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reacciones_publicacion PRIMARY KEY (id_reaccion),
    CONSTRAINT uq_reacciones_publicacion_usuario UNIQUE (id_publicacion, id_usuario),
    CONSTRAINT ck_reacciones_publicacion_tipo CHECK (
        tipo_reaccion IN ('ME_GUSTA', 'APOYO', 'CELEBRAR', 'INTERESA')
    )
);

CREATE TABLE publicaciones_guardadas (
    id_publicacion integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha_guardado timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_publicaciones_guardadas PRIMARY KEY (id_publicacion, id_usuario)
);

CREATE TABLE publicaciones_ocultas (
    id_publicacion integer NOT NULL,
    id_usuario integer NOT NULL,
    motivo varchar(150),
    fecha_ocultamiento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_publicaciones_ocultas PRIMARY KEY (id_publicacion, id_usuario)
);

CREATE TABLE bloqueos_usuarios (
    id_bloqueo integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_bloquea integer NOT NULL,
    id_usuario_bloqueado integer NOT NULL,
    motivo varchar(300),
    fecha_bloqueo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bloqueos_usuarios PRIMARY KEY (id_bloqueo),
    CONSTRAINT uq_bloqueos_usuarios_par UNIQUE (
        id_usuario_bloquea,
        id_usuario_bloqueado
    ),
    CONSTRAINT ck_bloqueos_usuarios_no_autobloqueo CHECK (
        id_usuario_bloquea <> id_usuario_bloqueado
    )
);

CREATE TABLE recomendaciones (
    id_recomendacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_recomienda integer NOT NULL,
    id_usuario_recomendado integer NOT NULL,
    id_trabajo integer,
    comentario varchar(700) NOT NULL,
    fecha_recomendacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_recomendacion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_recomendaciones PRIMARY KEY (id_recomendacion)
);

CREATE TABLE calificaciones (
    id_calificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_trabajo integer NOT NULL,
    id_calificador integer NOT NULL,
    id_calificado integer NOT NULL,
    puntuacion integer NOT NULL,
    comentario varchar(500),
    fecha_calificacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_calificaciones PRIMARY KEY (id_calificacion),
    CONSTRAINT uq_calificaciones_trabajo_participantes
        UNIQUE (id_trabajo, id_calificador, id_calificado),
    CONSTRAINT ck_calificaciones_puntuacion CHECK (puntuacion BETWEEN 1 AND 5)
);

CREATE TABLE conexiones_usuarios (
    id_conexion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_solicitante integer NOT NULL,
    id_usuario_receptor integer NOT NULL,
    estado_conexion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    mensaje varchar(300),
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_respuesta timestamp,
    CONSTRAINT pk_conexiones_usuarios PRIMARY KEY (id_conexion),
    CONSTRAINT uq_conexiones_usuarios_solicitante_receptor UNIQUE (id_usuario_solicitante, id_usuario_receptor),
    CONSTRAINT ck_conexiones_usuarios_no_autoconexion CHECK (id_usuario_solicitante <> id_usuario_receptor),
    CONSTRAINT ck_conexiones_usuarios_estado CHECK (
        estado_conexion IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')
    )
);

CREATE TABLE sesiones_usuario (
    id_sesion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    token_hash varchar(255) NOT NULL,
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp NOT NULL,
    fecha_cierre timestamp,
    estado_sesion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    CONSTRAINT pk_sesiones_usuario PRIMARY KEY (id_sesion),
    CONSTRAINT uq_sesiones_usuario_token_hash UNIQUE (token_hash)
);

CREATE TABLE tokens_recuperacion_password (
    id_token integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    token_hash varchar(255) NOT NULL,
    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion timestamp NOT NULL,
    usado boolean NOT NULL DEFAULT false,
    fecha_uso timestamp,
    CONSTRAINT pk_tokens_recuperacion_password PRIMARY KEY (id_token),
    CONSTRAINT uq_tokens_recuperacion_password_hash UNIQUE (token_hash)
);

CREATE TABLE verificaciones_usuario (
    id_verificacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    correo_institucional varchar(150) NOT NULL,
    codigo_verificacion varchar(20),
    estado_verificacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_verificacion timestamp,
    fecha_expiracion timestamp,
    ultima_revalidacion timestamp,
    tipo_verificacion varchar(50) NOT NULL,
    observacion varchar(300),
    CONSTRAINT pk_verificaciones_usuario PRIMARY KEY (id_verificacion)
);

-- Didit procesa el documento y la prueba de vida. T4KASH conserva solamente
-- identificadores, estados y fechas; no duplica fotografias ni datos biometricos.
CREATE TABLE verificaciones_identidad (
    id_verificacion_identidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    proveedor varchar(30) NOT NULL DEFAULT 'DIDIT',
    id_sesion_proveedor uuid NOT NULL,
    id_flujo_proveedor uuid,
    version_flujo integer,
    origen_solicitud varchar(30) NOT NULL DEFAULT 'PERFIL',
    estado_verificacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    estado_proveedor varchar(40) NOT NULL DEFAULT 'Not Started',
    huella_documento varchar(64),
    motivo_resultado varchar(500),
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_decision timestamp,
    fecha_expiracion timestamp,
    CONSTRAINT pk_verificaciones_identidad PRIMARY KEY (id_verificacion_identidad),
    CONSTRAINT uq_verificaciones_identidad_sesion UNIQUE (id_sesion_proveedor),
    CONSTRAINT ck_verificaciones_identidad_proveedor CHECK (
        proveedor ~ '^[A-Z][A-Z0-9_]{1,29}$'
    ),
    CONSTRAINT ck_verificaciones_identidad_origen CHECK (
        origen_solicitud IN ('PERFIL', 'WALLET', 'PAGO', 'TRABAJO', 'TAREA_RAPIDA', 'ADMIN')
    ),
    CONSTRAINT ck_verificaciones_identidad_estado CHECK (
        estado_verificacion IN (
            'PENDIENTE', 'EN_PROCESO', 'EN_REVISION', 'APROBADA', 'RECHAZADA',
            'EXPIRADA', 'VENCIDA', 'ABANDONADA', 'REQUIERE_ACCION', 'CANCELADA'
        )
    ),
    CONSTRAINT ck_verificaciones_identidad_version_flujo CHECK (
        version_flujo IS NULL OR version_flujo > 0
    ),
    CONSTRAINT ck_verificaciones_identidad_huella CHECK (
        huella_documento IS NULL OR huella_documento ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_verificaciones_identidad_fechas CHECK (
        fecha_actualizacion >= fecha_inicio
        AND (fecha_decision IS NULL OR fecha_decision >= fecha_inicio)
        AND (fecha_expiracion IS NULL OR fecha_expiracion > fecha_inicio)
    ),
    CONSTRAINT ck_verificaciones_identidad_decision CHECK (
        estado_verificacion NOT IN ('APROBADA', 'RECHAZADA')
        OR fecha_decision IS NOT NULL
    )
);

-- Cada entrega de webhook se registra con una clave idempotente. El contenido
-- sensible no se almacena; el hash permite auditar reintentos sin conservarlo.
CREATE TABLE eventos_webhook_identidad (
    id_evento_webhook_identidad integer GENERATED BY DEFAULT AS IDENTITY,
    id_verificacion_identidad integer NOT NULL,
    id_evento_proveedor varchar(150),
    clave_idempotencia varchar(64) NOT NULL,
    tipo_evento varchar(80) NOT NULL,
    estado_reportado varchar(40),
    firma_valida boolean NOT NULL DEFAULT false,
    estado_procesamiento varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    hash_contenido varchar(64) NOT NULL,
    fecha_recepcion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesamiento timestamp,
    detalle_error varchar(500),
    CONSTRAINT pk_eventos_webhook_identidad PRIMARY KEY (id_evento_webhook_identidad),
    CONSTRAINT uq_eventos_webhook_identidad_clave UNIQUE (clave_idempotencia),
    CONSTRAINT ck_eventos_webhook_identidad_clave CHECK (
        clave_idempotencia ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_eventos_webhook_identidad_hash CHECK (
        hash_contenido ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_eventos_webhook_identidad_estado CHECK (
        estado_procesamiento IN ('PENDIENTE', 'PROCESADO', 'IGNORADO', 'ERROR')
    ),
    CONSTRAINT ck_eventos_webhook_identidad_fechas CHECK (
        fecha_procesamiento IS NULL OR fecha_procesamiento >= fecha_recepcion
    )
);

CREATE TABLE intentos_login (
    id_intento integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer,
    correo varchar(150) NOT NULL,
    exitoso boolean NOT NULL,
    motivo_fallo varchar(150),
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_intento timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_intentos_login PRIMARY KEY (id_intento)
);

CREATE TABLE historial_estados (
    id_historial_estado integer GENERATED BY DEFAULT AS IDENTITY,
    entidad varchar(60) NOT NULL,
    id_entidad integer NOT NULL,
    estado_anterior varchar(40),
    estado_nuevo varchar(40) NOT NULL,
    id_usuario_cambio integer,
    motivo_cambio varchar(300),
    fecha_cambio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_historial_estados PRIMARY KEY (id_historial_estado)
);

CREATE TABLE reportes (
    id_reporte integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_reporta integer NOT NULL,
    id_usuario_reportado integer,
    id_tarea integer,
    id_publicacion integer,
    id_comentario_publicacion integer,
    motivo varchar(150) NOT NULL,
    descripcion varchar(700),
    estado_reporte varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_reporte timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_trabajo integer,
    id_entrega integer,
    id_pago integer,
    tipo_reporte varchar(30) NOT NULL,
    categoria_reporte varchar(80) NOT NULL,
    CONSTRAINT pk_reportes PRIMARY KEY (id_reporte)
);

CREATE TABLE sanciones_usuario (
    id_sancion integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario_sancionado integer NOT NULL,
    id_admin_responsable integer,
    id_reporte integer,
    id_disputa integer,
    nivel_sancion varchar(30) NOT NULL,
    alcance_sancion varchar(30) NOT NULL,
    origen_sancion varchar(20) NOT NULL DEFAULT 'MANUAL',
    motivo varchar(500) NOT NULL,
    estado_sancion varchar(30) NOT NULL DEFAULT 'ACTIVA',
    fecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_fin timestamp,
    fecha_revocacion timestamp,
    motivo_revocacion varchar(500),
    CONSTRAINT pk_sanciones_usuario PRIMARY KEY (id_sancion),
    CONSTRAINT ck_sanciones_usuario_nivel CHECK (
        nivel_sancion IN ('ADVERTENCIA', 'RESTRICCION', 'SUSPENSION', 'EXPULSION')
    ),
    CONSTRAINT ck_sanciones_usuario_alcance CHECK (
        alcance_sancion IN ('CUENTA', 'PUBLICAR', 'POSTULAR', 'CHAT', 'PAGOS', 'TOTAL')
    ),
    CONSTRAINT ck_sanciones_usuario_origen CHECK (
        origen_sancion IN ('AUTOMATICA', 'MANUAL')
    ),
    CONSTRAINT ck_sanciones_usuario_fechas CHECK (
        fecha_fin IS NULL OR fecha_fin > fecha_inicio
    )
);

CREATE TABLE apelaciones_sancion (
    id_apelacion integer GENERATED BY DEFAULT AS IDENTITY,
    id_sancion integer NOT NULL,
    id_usuario_solicita integer NOT NULL,
    id_admin_revisa integer,
    motivo_apelacion varchar(1000) NOT NULL,
    estado_apelacion varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_revision timestamp,
    resolucion varchar(1000),
    CONSTRAINT pk_apelaciones_sancion PRIMARY KEY (id_apelacion),
    CONSTRAINT ck_apelaciones_sancion_estado CHECK (
        estado_apelacion IN ('PENDIENTE', 'EN_REVISION', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')
    )
);

CREATE TABLE auditoria_sistema (
    id_auditoria integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer,
    accion varchar(100) NOT NULL,
    tabla_afectada varchar(100) NOT NULL,
    id_registro_afectado integer,
    datos_antes text,
    datos_despues text,
    ip_origen varchar(45),
    user_agent varchar(500),
    fecha_accion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditoria_sistema PRIMARY KEY (id_auditoria)
);

ALTER TABLE carreras
    ADD CONSTRAINT fk_carreras_universidades
    FOREIGN KEY (id_universidad) REFERENCES universidades (id_universidad);

ALTER TABLE dominios_universidad
    ADD CONSTRAINT fk_dominios_universidad_universidades
    FOREIGN KEY (id_universidad) REFERENCES universidades (id_universidad);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuarios_universidades
    FOREIGN KEY (id_universidad) REFERENCES universidades (id_universidad);

ALTER TABLE historial_nombres_usuario
    ADD CONSTRAINT fk_historial_nombres_usuario_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE metodos_cobro_usuario
    ADD CONSTRAINT fk_metodos_cobro_usuario_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_roles
    FOREIGN KEY (id_rol) REFERENCES roles (id_rol);

ALTER TABLE usuarios_estudiantes
    ADD CONSTRAINT fk_usuarios_estudiantes_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuarios_estudiantes
    ADD CONSTRAINT fk_usuarios_estudiantes_carreras
    FOREIGN KEY (id_carrera) REFERENCES carreras (id_carrera);

ALTER TABLE usuarios_habilidades
    ADD CONSTRAINT fk_usuarios_habilidades_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE usuarios_habilidades
    ADD CONSTRAINT fk_usuarios_habilidades_habilidades
    FOREIGN KEY (id_habilidad) REFERENCES habilidades (id_habilidad);

ALTER TABLE tareas
    ADD CONSTRAINT fk_tareas_categorias
    FOREIGN KEY (id_categoria) REFERENCES categorias_tarea (id_categoria);

ALTER TABLE tareas
    ADD CONSTRAINT fk_tareas_clientes
    FOREIGN KEY (id_cliente) REFERENCES usuarios (id_usuario);

ALTER TABLE tareas_habilidades
    ADD CONSTRAINT fk_tareas_habilidades_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE tareas_habilidades
    ADD CONSTRAINT fk_tareas_habilidades_habilidades
    FOREIGN KEY (id_habilidad) REFERENCES habilidades (id_habilidad);

ALTER TABLE postulaciones
    ADD CONSTRAINT fk_postulaciones_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE postulaciones
    ADD CONSTRAINT fk_postulaciones_usuarios_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE trabajos_asignados
    ADD CONSTRAINT fk_trabajos_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE trabajos_asignados
    ADD CONSTRAINT fk_trabajos_usuarios_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE entregas
    ADD CONSTRAINT fk_entregas_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE comentarios_entrega
    ADD CONSTRAINT fk_comentarios_entrega_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE comentarios_entrega
    ADD CONSTRAINT fk_comentarios_entrega_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE revisiones_entrega
    ADD CONSTRAINT fk_revisiones_entrega_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE revisiones_entrega
    ADD CONSTRAINT fk_revisiones_entrega_usuarios
    FOREIGN KEY (id_usuario_revisa) REFERENCES usuarios (id_usuario);

ALTER TABLE pagos
    ADD CONSTRAINT fk_pagos_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE pagos
    ADD CONSTRAINT fk_pagos_clientes
    FOREIGN KEY (id_cliente) REFERENCES usuarios (id_usuario);

ALTER TABLE pagos
    ADD CONSTRAINT fk_pagos_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE transacciones_pago
    ADD CONSTRAINT fk_transacciones_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE transacciones_pago
    ADD CONSTRAINT fk_transacciones_pago_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE eventos_webhook_pago
    ADD CONSTRAINT fk_eventos_webhook_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE disputas_pago
    ADD CONSTRAINT fk_disputas_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE disputas_pago
    ADD CONSTRAINT fk_disputas_pago_usuario_abre
    FOREIGN KEY (id_usuario_abre) REFERENCES usuarios (id_usuario);

ALTER TABLE disputas_pago
    ADD CONSTRAINT fk_disputas_pago_admin_asignado
    FOREIGN KEY (id_admin_asignado) REFERENCES usuarios (id_usuario);

ALTER TABLE eventos_disputa_pago
    ADD CONSTRAINT fk_eventos_disputa_pago_disputas
    FOREIGN KEY (id_disputa) REFERENCES disputas_pago (id_disputa);

ALTER TABLE eventos_disputa_pago
    ADD CONSTRAINT fk_eventos_disputa_pago_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE reembolsos_pago
    ADD CONSTRAINT fk_reembolsos_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE reembolsos_pago
    ADD CONSTRAINT fk_reembolsos_pago_disputas
    FOREIGN KEY (id_disputa) REFERENCES disputas_pago (id_disputa);

ALTER TABLE reembolsos_pago
    ADD CONSTRAINT fk_reembolsos_pago_usuarios
    FOREIGN KEY (id_usuario_solicita) REFERENCES usuarios (id_usuario);

ALTER TABLE desembolsos_pago
    ADD CONSTRAINT fk_desembolsos_pago_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE desembolsos_pago
    ADD CONSTRAINT fk_desembolsos_pago_estudiantes
    FOREIGN KEY (id_estudiante) REFERENCES usuarios_estudiantes (id_usuario);

ALTER TABLE desembolsos_pago
    ADD CONSTRAINT fk_desembolsos_pago_metodos_cobro
    FOREIGN KEY (id_metodo_cobro) REFERENCES metodos_cobro_usuario (id_metodo_cobro);

ALTER TABLE canjes_puntos
    ADD CONSTRAINT fk_canjes_puntos_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE canjes_puntos
    ADD CONSTRAINT fk_canjes_puntos_beneficios
    FOREIGN KEY (id_beneficio) REFERENCES catalogo_beneficios_puntos (id_beneficio);

ALTER TABLE canjes_puntos
    ADD CONSTRAINT fk_canjes_puntos_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE canjes_puntos
    ADD CONSTRAINT fk_canjes_puntos_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE movimientos_puntos
    ADD CONSTRAINT fk_movimientos_puntos_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE movimientos_puntos
    ADD CONSTRAINT fk_movimientos_puntos_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE movimientos_puntos
    ADD CONSTRAINT fk_movimientos_puntos_canjes
    FOREIGN KEY (id_canje) REFERENCES canjes_puntos (id_canje);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_postulaciones
    FOREIGN KEY (id_postulacion) REFERENCES postulaciones (id_postulacion);

ALTER TABLE conversaciones
    ADD CONSTRAINT fk_conversaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE mensajes
    ADD CONSTRAINT fk_mensajes_conversaciones
    FOREIGN KEY (id_conversacion) REFERENCES conversaciones (id_conversacion);

ALTER TABLE mensajes
    ADD CONSTRAINT fk_mensajes_usuarios
    FOREIGN KEY (id_usuario_emisor) REFERENCES usuarios (id_usuario);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_mensajes
    FOREIGN KEY (id_mensaje) REFERENCES mensajes (id_mensaje);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_comentarios_publicacion
    FOREIGN KEY (id_comentario_publicacion)
    REFERENCES comentarios_publicacion (id_comentario_publicacion);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_verificaciones
    FOREIGN KEY (id_verificacion) REFERENCES verificaciones_usuario (id_verificacion);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_disputas
    FOREIGN KEY (id_disputa) REFERENCES disputas_pago (id_disputa);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_apelaciones
    FOREIGN KEY (id_apelacion) REFERENCES apelaciones_sancion (id_apelacion);

ALTER TABLE archivos_adjuntos
    ADD CONSTRAINT fk_archivos_adjuntos_usuarios
    FOREIGN KEY (id_usuario_sube) REFERENCES usuarios (id_usuario);

ALTER TABLE notificaciones
    ADD CONSTRAINT fk_notificaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE portafolio
    ADD CONSTRAINT fk_portafolio_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE publicaciones
    ADD CONSTRAINT fk_publicaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE publicaciones
    ADD CONSTRAINT fk_publicaciones_origen
    FOREIGN KEY (id_publicacion_origen) REFERENCES publicaciones (id_publicacion);

ALTER TABLE comentarios_publicacion
    ADD CONSTRAINT fk_comentarios_publicacion_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE comentarios_publicacion
    ADD CONSTRAINT fk_comentarios_publicacion_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE comentarios_publicacion
    ADD CONSTRAINT fk_comentarios_publicacion_padre
    FOREIGN KEY (id_publicacion, id_comentario_padre)
    REFERENCES comentarios_publicacion (
        id_publicacion,
        id_comentario_publicacion
    );

ALTER TABLE reacciones_publicacion
    ADD CONSTRAINT fk_reacciones_publicacion_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE reacciones_publicacion
    ADD CONSTRAINT fk_reacciones_publicacion_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE publicaciones_guardadas
    ADD CONSTRAINT fk_publicaciones_guardadas_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE publicaciones_guardadas
    ADD CONSTRAINT fk_publicaciones_guardadas_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE publicaciones_ocultas
    ADD CONSTRAINT fk_publicaciones_ocultas_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE publicaciones_ocultas
    ADD CONSTRAINT fk_publicaciones_ocultas_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE bloqueos_usuarios
    ADD CONSTRAINT fk_bloqueos_usuarios_bloquea
    FOREIGN KEY (id_usuario_bloquea) REFERENCES usuarios (id_usuario);

ALTER TABLE bloqueos_usuarios
    ADD CONSTRAINT fk_bloqueos_usuarios_bloqueado
    FOREIGN KEY (id_usuario_bloqueado) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_usuario_recomienda
    FOREIGN KEY (id_usuario_recomienda) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_usuario_recomendado
    FOREIGN KEY (id_usuario_recomendado) REFERENCES usuarios (id_usuario);

ALTER TABLE recomendaciones
    ADD CONSTRAINT fk_recomendaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_calificador
    FOREIGN KEY (id_calificador) REFERENCES usuarios (id_usuario);

ALTER TABLE calificaciones
    ADD CONSTRAINT fk_calificaciones_calificado
    FOREIGN KEY (id_calificado) REFERENCES usuarios (id_usuario);

ALTER TABLE conexiones_usuarios
    ADD CONSTRAINT fk_conexiones_usuarios_solicitante
    FOREIGN KEY (id_usuario_solicitante) REFERENCES usuarios (id_usuario);

ALTER TABLE conexiones_usuarios
    ADD CONSTRAINT fk_conexiones_usuarios_receptor
    FOREIGN KEY (id_usuario_receptor) REFERENCES usuarios (id_usuario);

ALTER TABLE sesiones_usuario
    ADD CONSTRAINT fk_sesiones_usuario_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE tokens_recuperacion_password
    ADD CONSTRAINT fk_tokens_recuperacion_password_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE verificaciones_usuario
    ADD CONSTRAINT fk_verificaciones_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE verificaciones_identidad
    ADD CONSTRAINT fk_verificaciones_identidad_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE eventos_webhook_identidad
    ADD CONSTRAINT fk_eventos_webhook_identidad_verificaciones
    FOREIGN KEY (id_verificacion_identidad)
    REFERENCES verificaciones_identidad (id_verificacion_identidad);

ALTER TABLE intentos_login
    ADD CONSTRAINT fk_intentos_login_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE historial_estados
    ADD CONSTRAINT fk_historial_estados_usuarios
    FOREIGN KEY (id_usuario_cambio) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_usuario_reporta
    FOREIGN KEY (id_usuario_reporta) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_usuario_reportado
    FOREIGN KEY (id_usuario_reportado) REFERENCES usuarios (id_usuario);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_tareas
    FOREIGN KEY (id_tarea) REFERENCES tareas (id_tarea);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_publicaciones
    FOREIGN KEY (id_publicacion) REFERENCES publicaciones (id_publicacion);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_comentarios_publicacion
    FOREIGN KEY (id_comentario_publicacion)
    REFERENCES comentarios_publicacion (id_comentario_publicacion);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_trabajos
    FOREIGN KEY (id_trabajo) REFERENCES trabajos_asignados (id_trabajo);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_entregas
    FOREIGN KEY (id_entrega) REFERENCES entregas (id_entrega);

ALTER TABLE reportes
    ADD CONSTRAINT fk_reportes_pagos
    FOREIGN KEY (id_pago) REFERENCES pagos (id_pago);

ALTER TABLE sanciones_usuario
    ADD CONSTRAINT fk_sanciones_usuario_sancionados
    FOREIGN KEY (id_usuario_sancionado) REFERENCES usuarios (id_usuario);

ALTER TABLE sanciones_usuario
    ADD CONSTRAINT fk_sanciones_usuario_administradores
    FOREIGN KEY (id_admin_responsable) REFERENCES usuarios (id_usuario);

ALTER TABLE sanciones_usuario
    ADD CONSTRAINT fk_sanciones_usuario_reportes
    FOREIGN KEY (id_reporte) REFERENCES reportes (id_reporte);

ALTER TABLE sanciones_usuario
    ADD CONSTRAINT fk_sanciones_usuario_disputas
    FOREIGN KEY (id_disputa) REFERENCES disputas_pago (id_disputa);

ALTER TABLE apelaciones_sancion
    ADD CONSTRAINT fk_apelaciones_sancion_sanciones
    FOREIGN KEY (id_sancion) REFERENCES sanciones_usuario (id_sancion);

ALTER TABLE apelaciones_sancion
    ADD CONSTRAINT fk_apelaciones_sancion_solicitantes
    FOREIGN KEY (id_usuario_solicita) REFERENCES usuarios (id_usuario);

ALTER TABLE apelaciones_sancion
    ADD CONSTRAINT fk_apelaciones_sancion_administradores
    FOREIGN KEY (id_admin_revisa) REFERENCES usuarios (id_usuario);

ALTER TABLE auditoria_sistema
    ADD CONSTRAINT fk_auditoria_sistema_usuarios
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

CREATE INDEX idx_tareas_estado ON tareas (estado_tarea);
CREATE INDEX idx_tareas_estado_publicacion
    ON tareas (estado_tarea, fecha_publicacion DESC);
CREATE INDEX idx_tareas_rapidas_busqueda
    ON tareas (tipo_oportunidad, estado_tarea, latitud, longitud)
    WHERE tipo_oportunidad = 'RAPIDA'
      AND latitud IS NOT NULL
      AND longitud IS NOT NULL;
CREATE INDEX idx_dominios_universidad_universidad
    ON dominios_universidad (id_universidad, estado);
CREATE UNIQUE INDEX uq_usuarios_nombre_usuario
    ON usuarios (lower(nombre_usuario));
CREATE INDEX idx_historial_nombres_usuario_fecha
    ON historial_nombres_usuario (id_usuario, fecha_cambio DESC);
CREATE INDEX idx_metodos_cobro_usuario_estado
    ON metodos_cobro_usuario (id_usuario, estado_metodo);
CREATE UNIQUE INDEX uq_metodos_cobro_usuario_predeterminado
    ON metodos_cobro_usuario (id_usuario, moneda)
    WHERE predeterminado = true AND estado_metodo = 'ACTIVO';
CREATE INDEX idx_tareas_categoria ON tareas (id_categoria);
CREATE INDEX idx_tareas_cliente ON tareas (id_cliente);
CREATE INDEX idx_tareas_coordenadas ON tareas (latitud, longitud)
    WHERE latitud IS NOT NULL AND longitud IS NOT NULL;
CREATE INDEX idx_postulaciones_estudiante ON postulaciones (id_estudiante);
CREATE INDEX idx_postulaciones_estado ON postulaciones (estado_postulacion);
CREATE UNIQUE INDEX uq_postulaciones_pendiente
    ON postulaciones (id_tarea, id_estudiante)
    WHERE estado_postulacion = 'PENDIENTE';
CREATE INDEX idx_trabajos_estudiante ON trabajos_asignados (id_estudiante);
CREATE INDEX idx_entregas_trabajo ON entregas (id_trabajo);
CREATE INDEX idx_pagos_estado ON pagos (estado_pago);
CREATE INDEX idx_pagos_cliente_fecha ON pagos (id_cliente, fecha_creacion DESC);
CREATE INDEX idx_pagos_estudiante_fecha ON pagos (id_estudiante, fecha_creacion DESC);
CREATE INDEX idx_pagos_referencia_proveedor ON pagos (referencia_proveedor)
    WHERE referencia_proveedor IS NOT NULL;
CREATE INDEX idx_pagos_pendientes_expiracion ON pagos (fecha_expiracion)
    WHERE estado_pago = 'PENDIENTE_PAGO';
CREATE INDEX idx_transacciones_pago_pago_fecha
    ON transacciones_pago (id_pago, fecha_registro DESC);
CREATE INDEX idx_transacciones_pago_usuario_fecha
    ON transacciones_pago (id_usuario, fecha_registro DESC)
    WHERE id_usuario IS NOT NULL;
CREATE INDEX idx_eventos_webhook_estado_fecha
    ON eventos_webhook_pago (estado_procesamiento, fecha_recepcion);
CREATE INDEX idx_disputas_pago_estado_fecha
    ON disputas_pago (estado_disputa, fecha_apertura);
CREATE INDEX idx_disputas_pago_pago ON disputas_pago (id_pago);
CREATE UNIQUE INDEX uq_disputas_pago_activa
    ON disputas_pago (id_pago)
    WHERE estado_disputa IN ('ABIERTA', 'NEGOCIACION', 'ESPERANDO_EVIDENCIA', 'EN_REVISION');
CREATE INDEX idx_eventos_disputa_fecha
    ON eventos_disputa_pago (id_disputa, fecha_evento);
CREATE INDEX idx_reembolsos_pago_estado
    ON reembolsos_pago (estado_reembolso, fecha_solicitud);
CREATE INDEX idx_desembolsos_pago_estudiante_estado
    ON desembolsos_pago (id_estudiante, estado_desembolso, fecha_creacion DESC);
CREATE UNIQUE INDEX uq_desembolsos_pago_no_terminal
    ON desembolsos_pago (id_pago)
    WHERE estado_desembolso NOT IN ('FALLIDO', 'CANCELADO');
CREATE INDEX idx_canjes_puntos_usuario_fecha
    ON canjes_puntos (id_usuario, fecha_solicitud DESC);
CREATE INDEX idx_movimientos_puntos_usuario_fecha
    ON movimientos_puntos (id_usuario, fecha_movimiento DESC);
CREATE INDEX idx_movimientos_puntos_expiracion
    ON movimientos_puntos (fecha_expiracion)
    WHERE fecha_expiracion IS NOT NULL AND estado_movimiento = 'APLICADO';
CREATE INDEX idx_notificaciones_usuario_fecha
    ON notificaciones (id_usuario, fecha_creacion DESC);
CREATE INDEX idx_publicaciones_feed
    ON publicaciones (estado_publicacion, visibilidad, fecha_publicacion DESC);
CREATE INDEX idx_publicaciones_usuario_fecha
    ON publicaciones (id_usuario, fecha_publicacion DESC);
CREATE INDEX idx_publicaciones_origen
    ON publicaciones (id_publicacion_origen)
    WHERE id_publicacion_origen IS NOT NULL;
CREATE INDEX idx_comentarios_publicacion_fecha
    ON comentarios_publicacion (id_publicacion, fecha_comentario);
CREATE INDEX idx_comentarios_publicacion_usuario
    ON comentarios_publicacion (id_usuario, fecha_comentario DESC);
CREATE INDEX idx_reacciones_publicacion_tipo
    ON reacciones_publicacion (id_publicacion, tipo_reaccion);
CREATE INDEX idx_publicaciones_guardadas_usuario
    ON publicaciones_guardadas (id_usuario, fecha_guardado DESC);
CREATE INDEX idx_publicaciones_ocultas_usuario
    ON publicaciones_ocultas (id_usuario, fecha_ocultamiento DESC);
CREATE INDEX idx_bloqueos_usuarios_bloqueado
    ON bloqueos_usuarios (id_usuario_bloqueado);
CREATE INDEX idx_mensajes_conversacion_fecha
    ON mensajes (id_conversacion, fecha_envio DESC);
CREATE INDEX idx_mensajes_no_leidos
    ON mensajes (id_conversacion, id_usuario_emisor)
    WHERE leido = false;
CREATE UNIQUE INDEX uq_conversaciones_trabajo
    ON conversaciones (id_trabajo)
    WHERE id_trabajo IS NOT NULL;
CREATE UNIQUE INDEX uq_conversaciones_postulacion
    ON conversaciones (id_postulacion)
    WHERE id_postulacion IS NOT NULL;
CREATE UNIQUE INDEX uq_conexiones_usuarios_par
    ON conexiones_usuarios (
        LEAST(id_usuario_solicitante, id_usuario_receptor),
        GREATEST(id_usuario_solicitante, id_usuario_receptor)
    );
CREATE INDEX idx_archivos_verificacion ON archivos_adjuntos (id_verificacion)
    WHERE id_verificacion IS NOT NULL;
CREATE INDEX idx_archivos_apelacion ON archivos_adjuntos (id_apelacion)
    WHERE id_apelacion IS NOT NULL;
CREATE INDEX idx_reportes_estado_fecha
    ON reportes (estado_reporte, fecha_reporte DESC);
CREATE INDEX idx_reportes_usuario_fecha
    ON reportes (id_usuario_reporta, fecha_reporte DESC);
CREATE INDEX idx_sanciones_usuario_estado
    ON sanciones_usuario (id_usuario_sancionado, estado_sancion, fecha_inicio DESC);
CREATE INDEX idx_sanciones_usuario_vencimiento
    ON sanciones_usuario (fecha_fin)
    WHERE estado_sancion = 'ACTIVA' AND fecha_fin IS NOT NULL;
CREATE UNIQUE INDEX uq_apelaciones_sancion_activa
    ON apelaciones_sancion (id_sancion)
    WHERE estado_apelacion IN ('PENDIENTE', 'EN_REVISION');
CREATE INDEX idx_verificaciones_identidad_usuario_fecha
    ON verificaciones_identidad (id_usuario, fecha_inicio DESC);
CREATE INDEX idx_verificaciones_identidad_estado
    ON verificaciones_identidad (estado_verificacion, fecha_actualizacion);
CREATE UNIQUE INDEX uq_verificaciones_identidad_usuario_activa
    ON verificaciones_identidad (id_usuario)
    WHERE estado_verificacion IN (
        'PENDIENTE', 'EN_PROCESO', 'EN_REVISION', 'REQUIERE_ACCION'
    );
CREATE UNIQUE INDEX uq_verificaciones_identidad_huella_aprobada
    ON verificaciones_identidad (huella_documento)
    WHERE huella_documento IS NOT NULL
      AND estado_verificacion = 'APROBADA';
CREATE INDEX idx_eventos_webhook_identidad_pendientes
    ON eventos_webhook_identidad (estado_procesamiento, fecha_recepcion)
    WHERE estado_procesamiento IN ('PENDIENTE', 'ERROR');

-- Android consume la API Spring Boot. RLS bloquea el acceso directo mediante las
-- claves publicas de Supabase; el backend conserva acceso por su conexion de servidor.
DO $$
DECLARE
    nombre_tabla text;
BEGIN
    FOREACH nombre_tabla IN ARRAY ARRAY[
        'universidades', 'dominios_universidad', 'carreras', 'roles',
        'usuarios', 'usuario_roles',
        'usuarios_estudiantes', 'habilidades', 'usuarios_habilidades',
        'categorias_tarea', 'tareas', 'tareas_habilidades', 'postulaciones',
        'trabajos_asignados', 'entregas', 'comentarios_entrega',
        'revisiones_entrega', 'pagos', 'historial_nombres_usuario',
        'metodos_cobro_usuario', 'transacciones_pago', 'eventos_webhook_pago',
        'disputas_pago', 'eventos_disputa_pago', 'reembolsos_pago',
        'desembolsos_pago', 'catalogo_beneficios_puntos', 'canjes_puntos',
        'movimientos_puntos', 'conversaciones', 'mensajes', 'archivos_adjuntos',
        'notificaciones', 'portafolio', 'publicaciones',
        'comentarios_publicacion', 'reacciones_publicacion',
        'publicaciones_guardadas', 'publicaciones_ocultas', 'bloqueos_usuarios',
        'recomendaciones',
        'calificaciones', 'conexiones_usuarios', 'sesiones_usuario',
        'tokens_recuperacion_password', 'verificaciones_usuario',
        'verificaciones_identidad', 'eventos_webhook_identidad', 'intentos_login',
        'historial_estados', 'reportes', 'sanciones_usuario',
        'apelaciones_sancion', 'auditoria_sistema'
    ]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', nombre_tabla);
    END LOOP;
END $$;

INSERT INTO roles (id_rol, nombre_rol) VALUES
    (1, 'ADMIN'),
    (2, 'ESTUDIANTE'),
    (3, 'CLIENTE')
ON CONFLICT (id_rol) DO NOTHING;

INSERT INTO universidades (id_universidad, nombre_universidad, estado) VALUES
    (1, 'Universidad Americana', true),
    (2, 'Universidad Nacional Autonoma de Nicaragua, Managua', true),
    (3, 'Universidad Nacional de Ingenieria', true),
    (4, 'Universidad Nacional Autonoma de Nicaragua, Leon', true),
    (5, 'Universidad Catolica Redemptoris Mater', true)
ON CONFLICT (id_universidad) DO NOTHING;

INSERT INTO dominios_universidad (
    id_dominio,
    id_universidad,
    dominio_correo,
    tipo_dominio,
    verificacion_automatica,
    estado
) VALUES
    (1, 1, 'uamv.edu.ni', 'ESTUDIANTIL', true, true),
    (2, 1, 'uam.edu.ni', 'INSTITUCIONAL', false, true),
    (3, 2, 'unan.edu.ni', 'INSTITUCIONAL', true, true),
    (4, 3, 'uni.edu.ni', 'INSTITUCIONAL', true, true),
    (5, 4, 'ac.unanleon.edu.ni', 'INSTITUCIONAL', false, true),
    (6, 4, 'unanleon.edu.ni', 'GENERAL', false, true),
    (7, 5, 'unica.edu.ni', 'GENERAL', false, true)
ON CONFLICT (id_dominio) DO NOTHING;

INSERT INTO carreras (id_carrera, nombre_carrera, id_universidad) VALUES
    (1, 'Odontologia', 1),
    (2, 'Medicina', 1),
    (3, 'Psicologia', 1),
    (4, 'Nutricion', 1),
    (5, 'Marketing y Publicidad', 1),
    (6, 'Diseno y Comunicacion Visual', 1),
    (7, 'Comunicacion y Relaciones Publicas', 1),
    (8, 'Administracion de Empresas', 1),
    (9, 'Contabilidad y Finanzas', 1),
    (10, 'Economia Empresarial', 1),
    (11, 'Negocios Internacionales', 1),
    (12, 'Arquitectura', 1),
    (13, 'Ingenieria Civil', 1),
    (14, 'Ingenieria Industrial', 1),
    (15, 'Ingenieria en Sistemas de Informacion', 1),
    (16, 'Derecho', 1),
    (17, 'Diplomacia y Relaciones Internacionales', 1),
    (18, 'Arquitectura', 2),
    (19, 'Biologia', 2),
    (20, 'Matematica', 2),
    (21, 'Quimica Ambiental', 2),
    (22, 'Quimica Farmaceutica', 2),
    (23, 'Diseno Grafico y Multimedia', 2),
    (24, 'Informatica Educativa', 2),
    (25, 'Administracion de Empresas', 2),
    (26, 'Contaduria Publica y Finanzas', 2),
    (27, 'Economia', 2),
    (28, 'Marketing', 2),
    (29, 'Psicologia', 2),
    (30, 'Medicina', 2),
    (31, 'Enfermeria', 2),
    (32, 'Ingenieria en Sistemas', 2),
    (33, 'Arquitectura', 3),
    (34, 'Ingenieria Agricola', 3),
    (35, 'Ingenieria Civil', 3),
    (36, 'Ingenieria en Computacion', 3),
    (37, 'Ingenieria Electrica', 3),
    (38, 'Ingenieria Electronica', 3),
    (39, 'Ingenieria Industrial', 3),
    (40, 'Ingenieria Mecanica', 3),
    (41, 'Ingenieria Quimica', 3),
    (42, 'Ingenieria de Sistemas', 3),
    (43, 'Medicina', 4),
    (44, 'Bioanalisis Clinico', 4),
    (45, 'Odontologia', 4),
    (46, 'Ciencias de la Enfermeria', 4),
    (47, 'Psicologia', 4),
    (48, 'Farmacia', 4),
    (49, 'Medicina Veterinaria', 4),
    (50, 'Ingenieria en Agroecologia Tropical', 4),
    (51, 'Ingenieria Agropecuaria', 4),
    (52, 'Ingenieria en Agronegocios', 4),
    (53, 'Derecho', 4),
    (54, 'Administracion y Politicas Publicas', 4),
    (55, 'Ingenieria en Sistemas de Informacion', 4),
    (56, 'Administracion de Empresas', 4),
    (57, 'Contaduria Publica y Finanzas', 4),
    (58, 'Mercadotecnia', 4),
    (59, 'Economia', 4),
    (60, 'Gestion de Empresas Turisticas', 4),
    (61, 'Medicina', 5),
    (62, 'Odontologia', 5),
    (63, 'Derecho', 5),
    (64, 'Arquitectura', 5),
    (65, 'Pedagogia', 5),
    (66, 'Psicologia', 5),
    (67, 'Administracion de Empresas', 5),
    (68, 'Arte Digital y Animacion', 5),
    (69, 'Relaciones Internacionales y Comercio Internacional', 5),
    (70, 'Ingenieria Industrial', 5),
    (71, 'Marketing y Publicidad', 5),
    (72, 'Contabilidad y Finanzas', 5)
ON CONFLICT (id_carrera) DO NOTHING;

INSERT INTO categorias_tarea (id_categoria, nombre_categoria, descripcion, estado) VALUES
    (1, 'Tutoria', 'Apoyo academico por horas o sesiones.', true),
    (2, 'Desarrollo de software', 'Aplicaciones, sitios web, scripts y soporte tecnico.', true),
    (3, 'Diseno', 'Diseno grafico, UI, presentaciones y piezas digitales.', true),
    (4, 'Eventos', 'Apoyo logistico, voluntariado y actividades universitarias.', true),
    (5, 'Redaccion y traduccion', 'Correccion, redaccion academica y traduccion de contenidos.', true),
    (6, 'Fotografia y video', 'Cobertura de eventos, fotografia y edicion de imagen o video.', true),
    (7, 'Marketing digital', 'Contenido para redes, campanas y comunicacion digital.', true),
    (8, 'Soporte tecnologico', 'Instalacion, mantenimiento y ayuda con equipos o software.', true),
    (9, 'Investigacion', 'Busqueda de fuentes, levantamiento de datos y apoyo academico.', true),
    (10, 'Asistencia administrativa', 'Organizacion de documentos, digitacion y apoyo operativo.', true),
    (11, 'Idiomas', 'Clases, practica conversacional y revision de textos.', true),
    (12, 'Contabilidad', 'Registro de gastos, presupuestos y apoyo contable basico.', true),
    (13, 'Mascotas', 'Paseos, cuidado temporal, alimentacion y apoyo con mascotas.', true),
    (14, 'Hogar y mantenimiento', 'Limpieza, organizacion, reparaciones y mantenimiento basico.', true),
    (15, 'Transporte y entregas', 'Mandados, traslados y entrega local de productos o documentos.', true),
    (16, 'Ventas y atencion al cliente', 'Apoyo comercial, ventas, encuestas y servicio al cliente.', true),
    (17, 'Datos y analitica', 'Digitacion, limpieza, visualizacion y analisis de datos.', true),
    (18, 'Musica y audio', 'Grabacion, locucion, mezcla, edicion y apoyo musical.', true),
    (19, 'Salud y bienestar', 'Acompanamiento, actividad fisica y orientacion de bienestar no clinica.', true),
    (20, 'Asistencia legal', 'Organizacion documental e investigacion juridica bajo supervision.', true),
    (21, 'Arquitectura y construccion', 'Planos, presupuestos, levantamientos y apoyo en proyectos.', true),
    (22, 'Ambiente y sostenibilidad', 'Reciclaje, educacion ambiental y apoyo en proyectos sostenibles.', true),
    (23, 'Gastronomia', 'Preparacion de alimentos, reposteria y apoyo en servicios de comida.', true),
    (24, 'Deportes y actividad fisica', 'Entrenamiento, arbitraje y apoyo en actividades deportivas.', true)
ON CONFLICT (id_categoria) DO NOTHING;

INSERT INTO habilidades (id_habilidad, nombre_habilidad, descripcion, estado) VALUES
    (1, 'Kotlin', 'Desarrollo de aplicaciones Android.', true),
    (2, 'Java', 'Desarrollo backend y aplicaciones orientadas a objetos.', true),
    (3, 'Spring Boot', 'Creacion de APIs REST.', true),
    (4, 'PostgreSQL', 'Modelado y consultas de base de datos.', true),
    (5, 'Figma', 'Diseno de interfaces y prototipado.', true),
    (6, 'JavaScript', 'Desarrollo de soluciones web interactivas.', true),
    (7, 'TypeScript', 'Desarrollo web con tipado estatico.', true),
    (8, 'Python', 'Automatizacion, analisis de datos y desarrollo.', true),
    (9, 'React', 'Construccion de interfaces web por componentes.', true),
    (10, 'HTML y CSS', 'Maquetacion y estilos para sitios web.', true),
    (11, 'Git y GitHub', 'Control de versiones y colaboracion en repositorios.', true),
    (12, 'SQL', 'Consultas y manipulacion de datos relacionales.', true),
    (13, 'Microsoft Excel', 'Hojas de calculo, formulas y reportes.', true),
    (14, 'Power BI', 'Paneles e inteligencia de negocios.', true),
    (15, 'Canva', 'Creacion rapida de contenido visual.', true),
    (16, 'Adobe Photoshop', 'Edicion y composicion de imagenes.', true),
    (17, 'Adobe Illustrator', 'Ilustracion y diseno vectorial.', true),
    (18, 'Adobe Premiere Pro', 'Edicion profesional de video.', true),
    (19, 'Diseno UI/UX', 'Diseno de experiencias e interfaces digitales.', true),
    (20, 'Redaccion academica', 'Estructuracion y revision de textos academicos.', true),
    (21, 'Copywriting', 'Redaccion persuasiva para medios y negocios.', true),
    (22, 'Traduccion ingles-espanol', 'Traduccion general entre ingles y espanol.', true),
    (23, 'Ingles', 'Comunicacion oral y escrita en ingles.', true),
    (24, 'Fotografia', 'Captura y composicion fotografica.', true),
    (25, 'Edicion de video', 'Montaje y mejora de piezas audiovisuales.', true),
    (26, 'Gestion de redes sociales', 'Planificacion y administracion de contenido social.', true),
    (27, 'Marketing digital', 'Campanas, contenido y medicion digital.', true),
    (28, 'Atencion al cliente', 'Comunicacion y resolucion de solicitudes de clientes.', true),
    (29, 'Contabilidad', 'Registro, clasificacion y revision contable.', true),
    (30, 'Gestion administrativa', 'Organizacion documental y apoyo operativo.', true),
    (31, 'Analisis de datos', 'Limpieza, exploracion e interpretacion de datos.', true),
    (32, 'Estadistica', 'Analisis estadistico descriptivo e inferencial.', true),
    (33, 'Tutoria academica', 'Acompanamiento en procesos de aprendizaje.', true),
    (34, 'Organizacion de eventos', 'Planificacion y logistica de actividades.', true),
    (35, 'Oratoria', 'Presentacion clara de ideas ante una audiencia.', true),
    (36, 'Gestion de proyectos', 'Planificacion, seguimiento y entrega de proyectos.', true),
    (37, 'AutoCAD', 'Dibujo tecnico y elaboracion de planos.', true),
    (38, 'Dibujo tecnico', 'Representacion grafica de piezas y espacios.', true),
    (39, 'Soporte tecnico', 'Diagnostico y solucion de problemas tecnologicos.', true),
    (40, 'Mantenimiento de computadoras', 'Revision, limpieza y reparacion basica de equipos.', true)
ON CONFLICT (id_habilidad) DO NOTHING;

INSERT INTO catalogo_beneficios_puntos (
    id_beneficio,
    codigo_beneficio,
    nombre_beneficio,
    descripcion,
    costo_puntos,
    duracion_horas,
    tipo_destino,
    estado_beneficio
) VALUES
    (1, 'DESTACAR_TAREA_24H', 'Destacar tarea por 24 horas', 'Aumenta la visibilidad de una oportunidad durante 24 horas.', 100, 24, 'TAREA', 'ACTIVO'),
    (2, 'DESTACAR_PUBLICACION_24H', 'Destacar publicacion por 24 horas', 'Aumenta la visibilidad de una publicacion durante 24 horas.', 75, 24, 'PUBLICACION', 'ACTIVO'),
    (3, 'DESTACAR_PERFIL_7D', 'Destacar perfil por 7 dias', 'Muestra el perfil con mayor visibilidad durante siete dias.', 250, 168, 'PERFIL', 'ACTIVO')
ON CONFLICT (id_beneficio) DO NOTHING;

ALTER TABLE roles ALTER COLUMN id_rol RESTART WITH 4;
ALTER TABLE universidades ALTER COLUMN id_universidad RESTART WITH 6;
ALTER TABLE dominios_universidad ALTER COLUMN id_dominio RESTART WITH 8;
ALTER TABLE carreras ALTER COLUMN id_carrera RESTART WITH 73;
ALTER TABLE categorias_tarea ALTER COLUMN id_categoria RESTART WITH 25;
ALTER TABLE habilidades ALTER COLUMN id_habilidad RESTART WITH 41;
ALTER TABLE catalogo_beneficios_puntos ALTER COLUMN id_beneficio RESTART WITH 4;

COMMIT;
